notifications = {
  'none': 0,
  'user_status': 8,
  'transaction': 7,
  'new_swagger': 9,
  'swagger_deleted': 10,
  'peer_connection_update': 11,
  'invalid_credentials': 12,
  'favorite_deleted': 13,
  'network_update': 128,
  'message': 217,
  'ping': 208,
  'connection_enabled': -666,
  'suicide': 666,
}
