#!/usr/bin/env python3

from utils import *


with Meta() as meta:
  email = 'bob@infinit.io'
  fullname = 'bob'

  bob = User(meta, email = email, fullname = fullname)

  res = bob.get('devices/%s' % bob.device_id)
  assertEq(res['name'], str(bob.device_id))
  assertEq(res['id'], str(bob.device_id))
