#!/usr/bin/env python3

from utils import Meta, User


with Meta() as meta:
  email = 'bob@infinit.io'
  fullname = 'bob'

  bob = User(meta, email = email, fullname = fullname)

  bob.login()

  device = bob.post('device/create', {"name": "foobar"})

  assert device['success']
  assert device['name'] == "foobar"
  res = bob.get('devices/%s' % device['id'])

  assert res['name'] == device['name']
  assert res['id'] == device['id']
