#!/usr/bin/env python3

from utils import *
from infinit.oracles.meta import error
import uuid

with Meta() as meta:
  email = 'bob@infinit.io'
  fullname = 'bob'

  bob = User(meta, email = email, fullname = fullname)

  bob.login()

  foobar = bob.post('device/create', {"name": "foobar"})

  assert foobar['success']
  devices = bob.get('devices')['devices']

  assertEq(len(devices), 2)
  assertEq(devices[1]['id'], foobar['id'])

  device_id = devices[1]['id']

  foobar = bob.get('device/%s/view' % device_id)
  assert foobar['success']

  alice = User(meta, email = 'alice@infinit.io')
  alice.login()

  res = alice.get('device/%s/view' % device_id)
  print(res)
  assert res['error_code'] == error.DEVICE_NOT_FOUND[0]

  res = alice.post('device/delete', {'id': device_id})
  print(res)
  assert res['error_code'] == error.DEVICE_NOT_FOUND[0]

  res = bob.post('device/delete', {'id': foobar['id']})
  assert res['success']
  assert res['id'] == device_id

  devices = bob.get('devices')['devices']
  assert len(devices) == 1

  res = bob.get('device/%s/view' % device_id)
  assert res['error_code'] == error.DEVICE_NOT_FOUND[0]
