#!/usr/bin/env python3

from utils import Meta, User
from infinit.oracles.meta import error
import uuid

with Meta() as meta:
  email = 'bob@infinit.io'
  fullname = 'bob'

  bob = User(meta, email = email, fullname = fullname)

  bob.login()

  assert len(bob.devices) == 1

  foobar = bob.post('device/create', {"name": "foobar"})

  assert foobar['success']
  assert foobar['name'] == "foobar"

  barfoo = bob.post('device/create', {"name": "barfoo"})

  assert barfoo['success']
  assert barfoo['name'] == "barfoo"

  res = bob.get('devices')
  assert len(res['devices']) == 3

  assert set(d['id'] for d in res['devices']) == set([
      foobar['id'],
      barfoo['id'],
      str(bob.device_id),
    ])

  res = bob.get('device/%s/view' % uuid.uuid4()) # Not a valid id.
  assert res['error_code'] == error.DEVICE_NOT_FOUND[0]
