#!/usr/bin/env python3

from utils import Meta, User


with Meta() as meta:
  email = 'bob@infinit.io'
  fullname = 'bob'

  bob = User(meta, email = email, fullname = fullname)

  bob.login()

  foobar = bob.post('device/create', {"name": "foobar"})

  assert foobar['success']
  assert foobar['name'] == "foobar"

  res = bob.post('device/update', {'id': str(foobar['id']),
                                   'name': "barfoo"})
  print(res)
  assert res['success']
  assert res['name'] == "barfoo"
  assert res['id'] == foobar['id']
  assert res['passport'] == foobar['passport']
