#!/usr/bin/env python3

from utils import Meta, User
from infinit.oracles.meta import error
import uuid

with Meta() as meta:
  email = 'bob@infinit.io'
  fullname = 'bob'

  bob = User(meta, email = email, fullname = fullname)

  bob.login()

  foobar = bob.post('device/create', {"name": "foobar"})

  assert foobar['success']
  assert foobar['name'] == "foobar"

  res = bob.post('device/update', {'id': str(foobar['id']),
                                   'name': "barfoo"})
  print(res)
  assert res['success']
  assert res['name'] == "barfoo"
  assert res['id'] == foobar['id']
  assert res['passport'] == foobar['passport']

  res = bob.post('device/update', {'id': str(uuid.uuid4()),
                                   'name': "barfoo"})

  assert res['error_code'] == error.DEVICE_NOT_FOUND[0]
