#!/usr/bin/env python3

from utils import *
import bson

with Stripe() as stripe:
  with Meta(stripe_api_key = Stripe.key) as meta:
    test_suffix = stripe.suffix()
    jean = User(meta, 'jeantest_%s@infinit.io' % test_suffix)
    jean.login()
    def create():
      return jean.getalink(background = 'bg.jpg')
    throws(create, 402)
    jean.update_plan('premium', stripe_token = stripe.pay(jean.email))
    link = create()
    assertEq(meta.get('link/%s' % link['hash'])['background'], 'bg.jpg')
