#!/usr/bin/env python3

import datetime
from time import sleep

from utils import *
from bson.objectid import ObjectId
import infinit.oracles.meta.server.transaction_status as transaction_status

with Meta() as meta:
  alice = User(meta, 'alice@infinit.io')
  alice.login()
  pw = 'coinpanboumpaf'
  throws(lambda: alice.getalink(password = pw), 402)
  meta.meta.change_plan(bson.ObjectId(alice.id), 'premium')
  link = alice.getalink(password = pw)
  throws(lambda: meta.get('links/%s' % link['hash']), 401)
  throws(lambda: meta.get('links/%s?password=x' % link['hash']), 401)
  assertEq(
    link['id'],
    meta.get('links/%s?password=%s' % (link['hash'], pw))['id'])
  # Check one can read his own links without password
  assertEq(link['id'], alice.get('links/%s' % link['hash'])['id'])
