#!/usr/bin/env python3

from utils import *
import requests

with Stripe() as stripe:
  with Meta(stripe_api_key = Stripe.key) as meta:
    test_suffix = stripe.suffix()
    user = User(meta, 'user_%s@infinit.io' % test_suffix)
    user.login()
    link = user.getalink()
    view = meta.get('links/%s' % link['hash'])
    assertEq(view['owner_premium'], False)
    user.update_plan('premium', stripe_token = stripe.pay(user.email))
    view = meta.get('links/%s' % link['hash'])
    assertEq(view['owner_premium'], True)

    # Teams.
    admin = User(meta, 'team_admin_%s@infinit.io' % test_suffix)
    admin.login()
    team_name = 'infinit_%s' % test_suffix
    team = admin.create_team(
      name = team_name, stripe_token = stripe.pay(admin.email))
    link = admin.getalink()
    view = meta.get('links/%s' % link['hash'])
    assertEq(view['owner_premium'], True)
    member = User(meta, 'tema_member_%s@infinit.io' % test_suffix)
    member.login()
    admin.invite_team_member(member.email)
    member.join_team(team['id'])
    link = member.getalink()
    view = meta.get('links/%s' % link['hash'])
    assertEq(view['owner_premium'], True)
