#!/usr/bin/env python3

import os
import subprocess
import sys
import targets

os.chdir('%s' % os.environ['DIR_BUILD'])
subprocess.check_call(
  ['python3', 'drake', '-j', '3',] + list(targets.targets('build')))
