#!/usr/bin/env python3

import os
import subprocess
import sys

arch, osyst, compiler = os.environ['BUILDFARM_NAME'].split('-')

if osyst is "OSX":
    os.environ["CXXFLAGS"] = "-I/opt/local/include/ -L/opt/local/lib/"

prev = os.getcwd()
os.chdir('%s/dependencies' % os.environ['DIR_SOURCE'])
if osyst.startswith('linux') and arch == 'x86_64':
  if subprocess.call(['./build.sh', 'linux64']) != 0:
    exit(1)
elif osyst.startswith('macosx') and arch == 'x86_64':
  if subprocess.call(['./build.sh', 'macosx64']) != 0:
    exit(1)
else:
  raise Exception('unhandled OS / arch combination: %s, %s' % (osyst, arch))
os.chdir(prev)

os.chdir('%s' % os.environ['DIR_BUILD'])
if subprocess.call(['python3', 'drake', '//build']) != 0:
  exit(1)
