#!/usr/bin/env python3

import os
import subprocess
import sys

import targets

os.chdir(os.environ['DIR_BUILD'])
subprocess.check_call(
  ['python3', 'drake', '--prefix=../%s' % os.environ['DIR_INSTALL']]
  + list(targets.targets('install')))

# FIXME: use targets
if targets.osyst.startswith('linux'):
  subprocess.check_call(
    ['python3', 'drake', '--prefix=../%s' % os.environ['DIR_INSTALL'],
     '//oracles/apertus/server/debian',
     '//oracles/hephaestus/debian',
     '//oracles/meta/server/debian',
     '//oracles/trophonius/server/debian',
     '//fist-gui-qt/debian'
     '//oracles/sisyphus/debian',
   ])
if targets.osyst.startswith('osx'):
  subprocess.check_call(
    ['python3', 'drake', '--prefix=../%s' % os.environ['DIR_INSTALL'],
     '//surface/osx/package'])
