#!/usr/bin/env python3

import os
import subprocess
import sys
import targets

arch, osyst, comp = os.environ['BUILDFARM_NAME'].split('-')

os.chdir(os.environ['DIR_BUILD'])
jobs = os.environ['JOBS']
if osyst == 'osx':
  jobs = str(int(int(jobs) / 2))
subprocess.check_call(
  ['python3', 'drake', '-j', jobs] + list(targets.targets('check')))
