#!/usr/bin/env python3

import os, sys
sys.path.insert(
    0,
    os.path.abspath(
        os.path.join(os.path.dirname(__file__), '../../elle/drake/src')
    )
)
import resource

resource.setrlimit(resource.RLIMIT_NOFILE, (500, -1))

import drake
import drake.cxx
import drake.cxx.boost

cxx_compiler = os.getenv('CXX', 'g++')

cxx_toolkit = drake.cxx.GccToolkit(compiler = cxx_compiler)
cxx_config = drake.cxx.Config()
cxx_config.flag('-fPIC')
cxx_config.flag('-Wall')
cxx_config.flag('-m64') # XXX[to fix properly: we should have to specify this on a 64-bit machine]
cxx_config.flag('-mmacosx-version-min=10.7')
cxx_config.enable_debug_symbols()
cxx_config.enable_optimization(False)
cxx_config.add_system_include_path('.')

boost = drake.cxx.boost.Boost(prefix = '/opt/local')

drake.run(
    '../..',
    cxx_toolkit,
    cxx_config,
    boost = boost,
    qt = None,
    satellites = (
        "access", "group", "transfer",
        "sendto", "recvfrom", "progress",
        "d00m", "dump",
    ),
    python3 = '/opt/local/Library/Frameworks/Python.framework/Versions/3.2',
    build_type = os.environ.get('BUILD_TYPE', 'Development'),
)
