#!/usr/bin/env python3

import os
import sys
root = os.path.dirname(__file__)
drake = os.path.abspath(os.path.join(root, '../../elle/drake/src'))
sys.path.insert(0, drake)

import resource
resource.setrlimit(resource.RLIMIT_NOFILE, (500, -1))

import drake
import drake.cxx
import drake.cxx.boost

with drake.Drake('../..') as d:
  cxx_compiler = os.getenv('CXX', 'g++')
  cxx_toolkit = drake.cxx.GccToolkit(compiler = cxx_compiler)

  cxx_config = drake.cxx.Config()
  # XXX: to fix properly: we should have to specify this on a 64-bit
  # machine
  cxx_config.flag('-m64')
  cxx_config.flag('-mmacosx-version-min=10.7')
  cxx_config.enable_debug_symbols()
  cxx_config.enable_optimization(False)

  boost = drake.cxx.boost.Boost(prefix = '/opt/local')
  python = '/opt/local/python/Library/Frameworks/Python.framework/Versions/3.2'
  d.run(cxx_toolkit,
        cxx_config,
        boost = boost,
        python3 = python,
        build_type = os.environ.get('BUILD_TYPE', 'Development'))
