#! /usr/bin/env python3

import infinit.oracles.servers
import os
import utils
from utils import expect_raise


def main():
  with infinit.oracles.servers.Oracles(
      mongo_dump = '%s/one-user' % os.environ['DUMPS']) as o:
    s = o.state()
    expect_raise(lambda: s.login('mefyl@infinit.io', 'lol'))
    expect_raise(lambda: s.login('mefyl@infinit.com', 'mefyl'))
    s.login('mefyl@infinit.io',
            state.hash_password('mefyl@infinit.io', 'mefyl'))

utils.run(main)
