#!/usr/bin/env python3

import datetime

from utils import *
from infinit.oracles.meta import error

with Stripe() as stripe:
  # Ensure uniqueness for stripe.
  def __suffix():
    from random import randint
    return str(randint(1e9, 9e9))

  # Creating and deleting.
  with Meta(stripe_api_key = Stripe.key) as meta:
    test_suffix = __suffix()
    plan_id = 'team'
    leader = User(meta, 'boss_%s@infinit.io' % test_suffix)
    leader.login()
    team_name = 'infinit_%s' % test_suffix
    team = leader.create_team(
      name = team_name, stripe_token = stripe.pay(leader.email),
      plan = plan_id)
    throws(lambda: leader.create_team(
           name = 'fail', stripe_token = stripe.pay(leader.email)), 403)
    team = leader.get('team')
    assertEq(team['name'], team_name)
    assertEq(team['admin'], leader.id)
    assertEq(len(team['members']), 1)
    assertEq(team['members'][0], leader.id)
    stripe.check_plan(leader.email, plan_id, quantity = 1)
    throws(lambda: leader.delete('team'), 403)
    leader.delete('team', {'password': leader.password})
    throws(lambda: leader.get('team'), 404)
    stripe.check_plan(leader.email, plan_id, canceled = True)

  # Team uniqueness.
  with Meta(stripe_api_key = Stripe.key) as meta:
    test_suffix = __suffix()
    leader = User(meta, 'boss_%s@infinit.io' % test_suffix)
    leader.login()
    team = leader.create_team(
      name = 'infinit_%s' % test_suffix,
      stripe_token = stripe.pay(leader.email))
    # Leader already has a team.
    throws(lambda: leader.create_team(
      name = 'bombarde', stripe_token = stripe.pay(leader.email)),
           401)

  # Team name uniqueness.
  with Meta(stripe_api_key = Stripe.key) as meta:
    test_suffix = __suffix()
    leader = User(meta, 'boss_%s@infinit.io' % test_suffix)
    leader.login()
    original_name = 'infinit_%s' % test_suffix
    team = leader.create_team(
      name = original_name, stripe_token = stripe.pay(leader.email))
    bob = User(meta, 'bob_%s@infinit.io' % test_suffix)
    bob.login()
    throws(lambda: bob.create_team(
      name = original_name,
      stripe_token = stripe.pay(leader.email)),
           409)
    leader.put('team', {'name': 'bombarde_%s' % test_suffix})
    # original name is now available.
    bob.create_team(
      name = original_name, stripe_token = stripe.pay(bob.email))

  # Adding and removing users.
  with Meta(stripe_api_key = Stripe.key) as meta:
    test_suffix = __suffix()
    plan = meta.create_plan(stripe, 'plan_name_%s' % test_suffix, {})
    leader = User(meta, 'boss_%s@infinit.io' % test_suffix)
    leader.login()
    team = leader.create_team(
      name = 'infinit_%s' % test_suffix,
      stripe_token = stripe.pay(leader.email),
      plan = plan['id'])
    stripe.check_plan(leader.email, plan['id'], quantity = 1)
    # Invite an existing user.
    baptiste = User(meta, 'baptiste@infinit.io')
    leader.invite_team_member(baptiste.id)
    res = leader.get('team')
    assertEq(len(res['members']), 1)
    assertEq(len(res['invitees']), 1)
    stripe.check_plan(leader.email, plan['id'], quantity = 1)
    baptiste.login()
    baptiste.join_team(team['id'])
    res = leader.get('team')
    assertEq(len(res['members']), 2)
    assertEq(len(res['invitees']), 0)
    stripe.check_plan(leader.email, plan['id'], quantity = 2)
    raph = User(meta, 'raph@infinit.io')
    raph.login()
    # Join without invitation.
    throws(lambda: raph.join_team(team['id']), 403)
    # Invite.
    leader.invite_team_member(raph.id)
    res = leader.get('team')
    assertEq(len(res['members']), 2)
    assertEq(len(res['invitees']), 1)
    stripe.check_plan(leader.email, plan['id'], quantity = 2)
    raph.join_team(team['id'])
    res = leader.get('team')
    assertEq(len(res['members']), 3)
    assertEq(len(res['invitees']), 0)
    stripe.check_plan(leader.email, plan['id'], quantity = 3)
    # Delete a user.
    leader.delete_team_member(raph.id)
    assertEq(len(leader.get('team')['members']), 2)
    stripe.check_plan(leader.email, plan['id'], quantity = 2)
    # Reject invitation.
    jean = User(meta, 'jean@infinit.io')
    leader.invite_team_member(jean.id)
    res = leader.get('team')
    assertEq(len(res['members']), 2)
    assertEq(len(res['invitees']), 1)
    jean.login()
    jean.reject_invitation(team['id'])
    res = leader.get('team')
    assertEq(len(res['members']), 2)
    assertEq(len(res['invitees']), 0)
    # Uninvite.
    pierre = User(meta, 'pierre@infinit.io')
    leader.invite_team_member(pierre.id)
    res = leader.get('team')
    assertEq(len(res['members']), 2)
    assertEq(len(res['invitees']), 1)
    leader.uninvite_team_member(pierre.id)
    res = leader.get('team')
    assertEq(len(res['members']), 2)
    assertEq(len(res['invitees']), 0)

  # Default Team storage.
  with Meta(stripe_api_key = Stripe.key) as meta:
    with Trophonius(meta) as tropho:

      def check_account(account, plan, link_quota, link_usage = 0):
        assertEq(account['plan'], plan)
        link = account['quotas']['links']
        assertEq(link['quota'], link_quota)
        assertEq(link['used'], link_usage)

      def check_user(user, plan, link_quota, link_usage = 0):
        while len(user.notifications):
          notif = user.next_notification()
          # Only watch for model update notifications with the user's account.
          if notif.get('account'):
            check_account(notif['account'], plan, link_quota, link_usage)
        res = user.get('user/synchronize?init=1')
        check_account(res['account'], plan, link_quota, link_usage)

      def get_a_link(user, size):
        link = user.getalink(files = [('bite', size)])
        user.link_update(link, transaction_status.FINISHED)
        # Meta is updating quota by reading cloud storage file size which is
        # not realy uploaded here, so insert set the value manually.
        meta.database.links.update(
          {'hash': link['hash']},
          {'$set': {'file_size': size, 'quota_counted': True}})
        return link

      test_suffix = __suffix()
      plan_id = 'team'
      per_user = int(15e10)
      leader = User(meta, 'boss_%s@infinit.io' % test_suffix)
      members = [leader]
      leader.login(trophonius = tropho)
      team = leader.create_team(
        name = 'infinit_%s' % test_suffix,
        stripe_token = stripe.pay(leader.email),
        plan = plan_id)
      check_user(leader, plan_id, per_user)
      # Add first member.
      jean = User(meta, 'jean_%s@infinit.io' % test_suffix)
      jean.login(trophonius = tropho)
      leader.invite_team_member(jean.email)
      jean.join_team(team['id'])
      members.append(jean)
      for user in members:
        check_user(user, plan_id, per_user * 2)
      # Add second member.
      bob = User(meta, 'bob_%s@infinit.io' % test_suffix)
      bob.login(trophonius = tropho)
      leader.invite_team_member(bob.email)
      bob.join_team(team['id'])
      members.append(bob)
      for user in members:
        check_user(user, plan_id, per_user * 3)
      # Use some storage
      get_a_link(jean, 10)
      for user in members:
        check_user(user, plan_id, per_user * 3, 10)
      link = get_a_link(leader, 25)
      for user in members:
        check_user(user, plan_id, per_user * 3, 35)
      leader.link_update(link, transaction_status.DELETED)
      for user in members:
        check_user(user, plan_id, per_user * 3, 10)
      get_a_link(bob, 20)
      for user in members:
        check_user(user, plan_id, per_user * 3, 30)
      # Remove a member.
      leader.delete_team_member(jean.id)
      members.remove(jean)
      for user in members:
        check_user(user, plan_id, per_user * 2, 20)
      check_user(jean, 'basic', int(1e9), 10)

  # Custom Team storage.
  with Meta(stripe_api_key = Stripe.key) as meta:
    with Trophonius(meta) as tropho:

      def check_account(account, plan, link_quota, link_usage = 0):
        assertEq(account['plan'], plan)
        link = account['quotas']['links']
        assertEq(link['quota'], link_quota)
        assertEq(link['used'], link_usage)

      def check_user(user, plan, link_quota, link_usage = 0):
        while len(user.notifications):
          notif = user.next_notification()
          # Only watch for model update notifications with the user's account.
          if notif.get('account'):
            check_account(notif['account'], plan, link_quota, link_usage)
        res = user.get('user/synchronize?init=1')
        check_account(res['account'], plan, link_quota, link_usage)

      def get_a_link(user, size):
        link = user.getalink(files = [('bite', size)])
        user.link_update(link, transaction_status.FINISHED)
        # Meta is updating quota by reading cloud storage file size which is
        # not realy uploaded here, so insert set the value manually.
        meta.database.links.update(
          {'hash': link['hash']},
          {'$set': {'file_size': size, 'quota_counted': True}})
        return link

      test_suffix = __suffix()
      plan = meta.create_plan(stripe, 'plan_name_%s' % test_suffix, {})
      link_limit = int(1e11)
      leader = User(meta, 'boss_%s@infinit.io' % test_suffix)
      members = [leader]
      leader.login(trophonius = tropho)
      team = leader.create_team(
        name = 'infinit_%s' % test_suffix,
        stripe_token = stripe.pay(leader.email),
        plan = plan['id'])
      check_user(leader, 'team', link_limit)
      # Add first member.
      jean = User(meta, 'jean_%s@infinit.io' % test_suffix)
      jean.login(trophonius = tropho)
      leader.invite_team_member(jean.email)
      jean.join_team(team['id'])
      members.append(jean)
      for user in members:
        check_user(user, 'team', link_limit)
      # Add second member.
      bob = User(meta, 'bob_%s@infinit.io' % test_suffix)
      bob.login(trophonius = tropho)
      leader.invite_team_member(bob.email)
      bob.join_team(team['id'])
      members.append(bob)
      for user in members:
        check_user(user, 'team', link_limit)
      # Use some storage
      get_a_link(jean, 10)
      for user in members:
        check_user(user, 'team', link_limit, 10)
      link = get_a_link(leader, 25)
      for user in members:
        check_user(user, 'team', link_limit, 35)
      leader.link_update(link, transaction_status.DELETED)
      for user in members:
        check_user(user, 'team', link_limit, 10)
      get_a_link(bob, 20)
      for user in members:
        check_user(user, 'team', link_limit, 30)
      # Remove a member.
      leader.delete_team_member(jean.id)
      members.remove(jean)
      for user in members:
        check_user(user, 'team', link_limit, 20)
      check_user(jean, 'basic', int(1e9), 10)

  # Team view as member.
  with Meta(stripe_api_key = Stripe.key) as meta:
    test_suffix = __suffix()
    leader = User(meta, 'boss_%s@infinit.io' % test_suffix)
    leader.login()
    team = leader.create_team(
      name = 'infinit', stripe_token = stripe.pay(leader.email))
    baptiste = User(meta, 'baptiste_%s@infinit.io' % test_suffix)
    leader.invite_team_member(baptiste.id)
    baptiste.login()
    baptiste.join_team(team['id'])
    # Get info about the team as non leader.
    team = baptiste.get('team')
    assertEq(len(team['members']), 2)
    assertEq(team['admin'], leader.id)

  # Deleting a team should remove all members.
  with Meta(stripe_api_key = Stripe.key) as meta:
    test_suffix = __suffix()
    plan = meta.create_plan(stripe, 'plan_name_%s' % test_suffix, {})
    leader = User(meta, 'boss_%s@infinit.io' % test_suffix)
    leader.login()
    team = leader.create_team(
      name = 'infinit_%s' % test_suffix,
      stripe_token = stripe.pay(leader.email),
      plan = plan['id'])
    baptiste = User(meta, 'baptiste_%s@infinit.io' % test_suffix)
    leader.invite_team_member(baptiste.id)
    baptiste.login()
    baptiste.join_team(team['id'])
    team = leader.get('team')
    assertEq(len(team['members']), 2)
    stripe.check_plan(leader.email, plan['id'], quantity = 2)
    assertEq(team['admin'], leader.id)
    leader.delete('team', {'password': leader.password})
    stripe.check_plan(leader.email, plan['id'], canceled = True)
    throws(lambda: baptiste.get('team'), 404)
    throws(lambda: leader.get('team'), 404)

  # Invite user who already has a team (and get out of a team).
  with Meta(stripe_api_key = Stripe.key) as meta:
    test_suffix = __suffix()
    leader = User(meta, 'boss_%s@infinit.io' % test_suffix)
    leader.login()
    plan_infinit = \
      meta.create_plan(stripe, 'plan_infinit_name_%s' % test_suffix, {})
    team_infinit = leader.create_team(
      name = 'infinit_%s' % test_suffix,
      stripe_token = stripe.pay(leader.email),
      plan = plan_infinit['id'])
    dropbox = User(meta, 'boss_%s@dropbox.com' % test_suffix)
    dropbox.login()
    plan_dropbox = \
      meta.create_plan(stripe, 'plan_dropbox_name_%s' % test_suffix, {})
    team_dropbox = dropbox.create_team(
      name = 'dropbox_%s' % test_suffix,
      stripe_token = stripe.pay(dropbox.email),
      plan = plan_dropbox['id'])
    invitee = User(meta, 'invitee_%s@infinit.io' % test_suffix)
    invite_guido = lambda x: x.invite_team_member(invitee.id)
    # Invite to first team.
    invite_guido(dropbox)
    res = dropbox.get('team')
    assertEq(len(res['members']), 1)
    assertEq(len(res['invitees']), 1)
    # Invite to second team.
    invite_guido(leader)
    res = leader.get('team')
    assertEq(len(res['members']), 1)
    assertEq(len(res['invitees']), 1)
    invitee.login()
    # Join first team.
    invitee.join_team(team_dropbox['id'])
    res = dropbox.get('team')
    assertEq(len(res['members']), 2)
    assertEq(len(res['invitees']), 0)
    res = leader.get('team')
    assertEq(len(res['members']), 1)
    assertEq(len(res['invitees']), 1)
    assertEq(invitee.get('team')['name'], team_dropbox['name'])
    # Try to join second team.
    throws(lambda: invitee.join_team(team_infinit['id']), 409)
    throws(lambda: invitee.post('team/leave'), 401)
    invitee.post('team/leave', {'password': invitee.password})
    assertEq(len(dropbox.get('team')['members']), 1)
    stripe.check_plan(dropbox.email, plan_dropbox['id'], quantity = 1)
    invitee.join_team(team_infinit['id'])
    assertEq(invitee.get('team')['name'], team_infinit['name'])
    res = leader.get('team')
    assertEq(len(res['members']), 2)
    assertEq(len(res['invitees']), 0)
    stripe.check_plan(leader.email, plan_infinit['id'], quantity = 2)

  # Admin exiting plan.
  with Meta(stripe_api_key = Stripe.key) as meta:
    test_suffix = __suffix()
    plan = meta.create_plan(
      stripe,
      'plan_name_%s' % test_suffix,
      {},
      amount = 10)
    leader = User(meta, 'boss_%s@infinit.io' % test_suffix)
    leader.login()
    leader.update_plan('premium', stripe_token = stripe.pay(leader.email))
    assertEq(leader.me['plan'], 'premium')
    stripe.check_plan(leader.email, 'premium', 999)
    leader.create_team(
      name = 'infinit_%s' % test_suffix,
      stripe_token = stripe.pay(leader.email),
      plan = plan['id'])
    stripe.check_plan(leader.email, plan['id'], 10, quantity = 1)

  # User existing plan.
  with Meta(stripe_api_key = Stripe.key) as meta:
    test_suffix = __suffix()
    plan = meta.create_plan(
      stripe,
      'plan_name_%s' % test_suffix,
      {},
      amount = 10)
    leader = User(meta, 'boss_%s@infinit.io' % test_suffix)
    leader.login()
    team = leader.create_team(
      name = 'infinit_%s' % test_suffix,
      stripe_token = stripe.pay(leader.email),
      plan = plan['id'])
    stripe.check_plan(leader.email, plan['id'], 10, quantity = 1)
    member = User(meta, 'bob_%s@infinit.io' % test_suffix)
    member.login()
    member.update_plan('premium', stripe_token = stripe.pay(member.email))
    stripe.check_plan(member.email, 'premium', 999)
    leader.invite_team_member(member.email)
    member.join_team(team['id'])
    stripe.check_plan(leader.email, plan['id'], 10, quantity = 2)
    # Member plan should be canceled prorata.
    stripe.check_no_plan(member.email)

  # Delete user who is part of team.
  with Meta(stripe_api_key = Stripe.key) as meta:
    test_suffix = __suffix()
    plan = meta.create_plan(
      stripe,
      'plan_name_%s' % test_suffix,
      {},
      amount = 10)
    leader = User(meta, 'boss_%s@infinit.io' % test_suffix)
    leader.login()
    team = leader.create_team(
      name = 'infinit_%s' % test_suffix,
      stripe_token = stripe.pay(leader.email),
      plan = plan['id'])
    stripe.check_plan(leader.email, plan['id'], 10, quantity = 1)
    another_leader = User(meta, 'bob_%s@infinit.io' % test_suffix)
    another_leader.login()
    another_leader.create_team(
      name = 'another_%s' % test_suffix,
      stripe_token = stripe.pay(another_leader),
      plan = plan['id'])
    stripe.check_plan(another_leader.email, plan['id'], 10, quantity = 1)
    member = User(meta, 'jean_%s@infinit.io' % test_suffix)
    member.login()
    leader.invite_team_member(member.email)
    another_leader.invite_team_member(member.email)
    assertEq(len(another_leader.get('team')['invitees']), 1)
    member.join_team(team['id'])
    assertEq(len(leader.get('team')['members']), 2)
    stripe.check_plan(leader.email, plan['id'], 10, quantity = 2)
    member.delete('user')
    assertEq(len(leader.get('team')['members']), 1)
    stripe.check_plan(leader.email, plan['id'], 10, quantity = 1)
    assertEq(len(another_leader.get('team')['invitees']), 0)

  # Delete user admin of team.
  with Meta(stripe_api_key = Stripe.key) as meta:
    test_suffix = __suffix()
    plan = meta.create_plan(
      stripe,
      'plan_name_%s' % test_suffix,
      {},
      amount = 10)
    leader = User(meta, 'boss_%s@infinit.io' % test_suffix)
    leader.login()
    team = leader.create_team(
      name = 'infinit_%s' % test_suffix,
      stripe_token = stripe.pay(leader.email),
      plan = plan['id'])
    throws(lambda: leader.delete('user'), 403)
    leader.delete('team', {'password': leader.password})
    leader.delete('user')

  # Change admin user's email address.
  with Meta(stripe_api_key = Stripe.key) as meta:
    # Pasted from auxiliary_emails
    class MailService(NoOpMailer):

      def __init__(self):
        self.change_email = {}
        super().__init__(True)

      def template_message(self, template_message, message):
        merges = {}
        for entry in message['merge_vars'][0]['vars']:
          merges[entry['name']] = entry['content']
        if template_message == 'change-email-address':
           self.change_email.update(
             {
               merges['new_email_address']: merges['hash']
             })

    def get_keys(emails, size):
      assertEq(len(emails), size)
      keys = {}
      for email in emails:
        keys[email.variables['email']] = email.variables['confirm_token']
      return keys

    test_suffix = __suffix()
    original_email = 'first_email_%s@infinit.io' % test_suffix
    leader = User(meta, original_email)
    leader.login()
    team = leader.create_team(
      name = 'infinit_%s' % test_suffix,
      stripe_token = stripe.pay(leader.email))
    stripe.check_plan(leader.email, 'team', 100, quantity = 1)
    new_email = 'jean_pierre_%s@infinit.io' % test_suffix
    leader.put('user/accounts/%s' % new_email)
    keys = get_keys(meta.emailer.emails, 1)
    leader.post(
      'users/%s/accounts/%s/confirm' % (leader.email, new_email),
      {'confirm_token': keys[new_email.lower()]})
    leader.get('users/%s' % new_email)
    leader.post('user/accounts/%s/make_primary' % new_email, {
      'password': leader.password
    })
    stripe.check_plan(new_email, 'team', 100, quantity = 1)
    # Add email address to stripe list for cleanup.
    stripe.emails.add(new_email)
    throws(lambda: stripe.customer_with_email(original_email), StripeTestException)


  # XXX: Add tests for all admin functions calls.

  # # Infinit administration.
  # with Meta(stripe_api_key = Stripe.key) as meta:
  #   test_suffix = __suffix()
  #   leader = User(meta, 'leader_%s@infinit.io' % test_suffix)
  #   leader.login()
  #   plan = meta.create_plan(stripe, 'plan_name_%s' % test_suffix, {})
  #   team = leader.create_team(
  #     name = 'infinit_%s' % test_suffix,
  #     stripe_token = stripe.pay(leader.email),
  #     plan = plan['id'])
  #   # View.
  #   admin_view = admin.get('team/%s' % team['id'])
  #   # XXX: Do the correct checks.
  #   # Rename.
  #   renamed_team = admin.put('team/%s' % team['id'], {'name': 'Bombarde'})
  #   assertEq(renamed_team['name'], 'Bombarde')
  #   # Add user.
  #   baptiste = User(meta, 'baptiste@infinit.io')
  #   leader.add_team_member(baptiste.id)
  #   # Get info about the team as non leader.
  #   baptiste.login()
  #   team = baptiste.get('team')
  #   assertEq(len(team['members']), 2)
  #   assertEq(team['admin'], leader.id)
  #   leader.delete('team', {'password': leader.password})
  #   throws(lambda: baptiste.get('team'), 404)
  #   throws(lambda: leader.get('team'), 404)
  #   updated_team = admin.put('team/%s/members/%s' % (team['id'], baptiste.id))
  #   assert user_in_team(updated_team, baptiste)
  #   assert user_in_team(leader.get('team'), baptiste)
  #   # Remove user.
  #   updated_team = admin.delete('team/%s/members/%s' %
  #                               (team['id'], baptiste.id))
  #   assert not user_in_team(updated_team, baptiste)
  #   assert not user_in_team(leader.get('team'), baptiste)
