#!/usr/bin/env python3

import os, sys
sys.path.insert(
    0,
    os.path.abspath(
        os.path.join(os.path.dirname(__file__), '../../elle/drake/src')
    )
)

import drake
import drake.cxx

cxx_toolkit = drake.cxx.GccToolkit(compiler = '/usr/bin/clang')

cxx_config = drake.cxx.Config()
cxx_config.enable_debug_symbols()
cxx_config.enable_optimization(False)
cxx_config.flag('-ftemplate-depth=512')
cxx_config.warnings.overloaded_virtual = False

drake.run('../..', cxx_toolkit, cxx_config, build_type = "Development")
