#!/usr/bin/env python2.7
# -*- encoding: utf-8 -*-

import sys, os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../lib/python"))

from apertus.application import Application

if __name__ == '__main__':
    kw = {}
    if len(sys.argv) > 1:
        args = sys.argv[1:]
        if ':' in  args[0]:
            kw['ip'], kw['port'] = args[0].split(':')
        else:
            try:
                kw['port'] = int(args[0])
            except:
                kw['ip'] = args[0]
    from trophonius.application import Application
    application = Application(**kw)
    application.run()
