#!/usr/bin/env python2.7
# -*- encoding: utf-8 -*-

import sys, os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../lib/python"))

from apertus.application import Application

if __name__ == '__main__':
    application = Application("0.0.0.0", 9898)
    application.run()
