#!/usr/bin/env python2.7
# -*- encoding: utf-8 -*-

import sys, os
import argparse
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../lib/python"))
import meta.conf
parser = argparse.ArgumentParser(description="Trophonius launcher")

parser.add_argument(
    '--port', type = int, default = meta.conf.APERTUS_PORT
)

parser.add_argument(
    '--runtime-dir', type = str, default = ""
)

from apertus.application import Application

if __name__ == '__main__':
    args = parser.parse_args()
    application = Application(
        port = args.port,
        runtime_dir = args.runtime_dir
    )
    application.run()
