#!/usr/bin/env python2.7


"""Meta server provide a JSON-RPC API to infinit
users, networks and devices managment.

"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../lib/python"))

from meta.application import Application

if __name__ == '__main__':
    app = Application("0.0.0.0")
    app.run()
