#!/usr/bin/env python2.7
# -*- encoding: utf-8 -*-

"""
trophonius-server provide a message queue to infinit clients.

Trophonius (the Latinate spelling) or Trophonios (the transliterated Greek
spelling of Τροφώνιος) was a Greek hero or daimon or god—it was never certain
which one—with a rich mythological tradition and an oracular cult at Lebadaea
in Boeotia.

"""

import sys, os
import argparse
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../lib/python"))
import meta.conf
import pythia.constants
parser = argparse.ArgumentParser(description="Trophonius launcher")

parser.add_argument(
    '--port', type = int, default = meta.conf.TROPHONIUS_PORT
)

# XXX Trophonius timeout is linked to plasma/trophonius/Client ping interval.
# As such, this value must always be greater than the client ping interval.
parser.add_argument(
    '--timeout',
    type = int,
    default = 60
)

parser.add_argument(
    '--host',
    default = meta.conf.TROPHONIUS_HOST
)

parser.add_argument(
    '--control-port',
    type = int,
    default = meta.conf.TROPHONIUS_CONTROL_PORT
)

parser.add_argument(
    '--meta-url',
    type = str,
    default = pythia.constants.DEFAULT_SERVER
)

parser.add_argument(
    '--runtime-dir',
    type = str,
    default = None
)

if __name__ == '__main__':
    args = parser.parse_args()
    from trophonius.application import Application
    application = Application(
        ip = args.host,
        port = args.port,
        ssl_port = args.control_port,
        meta_url = args.meta_url,
        runtime_dir = args.runtime_dir,
        timeout = args.timeout,
    )
    application.run()
