#!/usr/bin/env python2.7
# -*- encoding: utf-8 -*-

"""
trophonius-server provide a message queue to infinit clients.

Trophonius (the Latinate spelling) or Trophonios (the transliterated Greek
spelling of Τροφώνιος) was a Greek hero or daimon or god—it was never certain
which one—with a rich mythological tradition and an oracular cult at Lebadaea
in Boeotia.

"""

import sys, os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../lib/python"))

if __name__ == '__main__':
    kw = {}
    if len(sys.argv) > 1:
        args = sys.argv[1:]
        if ':' in  args[0]:
            kw['ip'], kw['port'] = args[0].split(':')
        else:
            try:
                kw['port'] = int(args[0])
            except:
                kw['ip'] = args[0]
    from trophonius.application import Application
    application = Application(**kw)
    application.run()
