#!/usr/bin/env python3

from utils import Meta, User
from infinit.oracles.meta import error

class MailService():

  def __init__(self, response):
    self.response = response

  def send_via_mailchimp(self,
                         mail,
                         template_id,
                         subject,
                         from_="Infinit <no-reply@infinit.io>",
                         reply_to=None,
                         encoding='utf8',
                         **kw):
    assert response['email'] == mail
    assert template_id == 'invitation-beta'

  def send(self,
           email,
           subject,
           content,
           from_="Infinit <no-reply@infinit.io>",
           reply_to=None,
           encoding='utf8',
           attached=None):
    self.response['email'] = email
    self.response['subject'] = subject
    self.response['content'] = content

with Meta() as meta:
  email = 'foobar@infinit.io'
  fullname = 'jean louis'

  response = {"email": "alice@infinit.io"}
  meta.mailer = MailService(response)

  query = {
    'email': email,
    'password': 'o' * 64,
    'fullname': fullname
  }

  res = meta.post('user/register', query)
  assert res['success']

  query.pop('fullname')
  res = meta.post('web-login', query)
  assert res['success']

  res = meta.post('user/invite', {"email": response['email']})
  assert res['success']

  res = meta.get('user/invited')
  assert res['success']
  assert res['user'] == [response['email']]
