#!/usr/bin/env python3

from utils import Meta, User, NoOpMailer

class MailService(NoOpMailer):

  def __init__(self, response):
    super().__init__()
    self.response = response

  def template_message(self, template_name, message):
    assert response['email'] == message['to'][0]['email']
    assert template_name == 'send-invitation-no-file'

with Meta() as meta:
  email = 'foobar@infinit.io'
  fullname = 'jean louis'

  response = {"email": "alice@infinit.io"}

  query = {
    'email': email,
    'password': 'o' * 64,
    'fullname': fullname
  }

  res = meta.post('user/register', query)
  assert res['success']

  query.pop('fullname')
  res = meta.post('web-login', query)
  assert res['success']

  meta.mailer = MailService(response)
  res = meta.post('user/invite', {"email": response['email']})
  assert res['success']

  res = meta.get('user/invited')
  assert res['success']
  print(res)
  assert res['user'] == [response['email']]
