#!/usr/bin/env python3

import utils

from utils import Meta, User
from infinit.oracles.meta import error

with Meta() as meta:
  email = 'foobar@infinit.io'
  fullname = 'jean louis'

  query = {
    'email': email,
    'password': 'o' * 64,
    'fullname': 'jeanlouis',
  }

  res = meta.post("user/register", query)
  assert res['success']

  query.pop('fullname')
  res = meta.post("web-login", query)
  assert res['success']

  # Check email with space.
  res = meta.post('web-login', {
    'email': ('%s ' % email),
    'password': 'o' * 64,
  })
  assert res['success']

  query['password'] = 'i' * 64
  try:
    res = meta.post("web-login", query)
  except utils.HTTPException as e:
    assert e.status == 403
  else:
    raise Exception('invalid login should have yield 403 forbidden')
