#!/usr/bin/env python3

from utils import *
from infinit.oracles.meta import error

with Meta() as meta:
  email = 'foobar@infinit.io'
  fullname = 'jean louis'

  query = {
    'email': email,
    'password': 'o' * 64,
    'fullname': 'jeanlouis',
  }

  res = meta.post("user/register", query)
  assert res['success']

  res = meta.post("user/register", query)
  assert not res['success']
  assert res['error_code'] == error.EMAIL_ALREADY_REGISTERED[0]

  query['email'] = 'heab'
  throws(lambda: meta.post("user/register", query), 400)

  query['email'] = 'bob@infinit.io'
  query['fullname'] = 'j'

  res = meta.post("user/register", query)
  assert not res['success']
  assert res['error_code'] == error.FULLNAME_NOT_VALID[0]

  # Check register with space.
  email = 'foobar2@infinit.io '
  fullname = 'jean louis'

  query = {
    'email': email,
    'password': 'o' * 64,
    'fullname': 'jeanlouis',
  }
  res = meta.post("user/register", query)
  assert res['success']
  correct_email = email.replace(' ', '')
  assert meta.database.users.find({'email': correct_email}).count() == 1
