#!/usr/bin/env python3

import os.path
import sys

SELF = os.path.realpath(__file__)
SELF_DIR = os.path.dirname(SELF)
sys.path.insert(0, '%s/../lib/python%s.%s' % (SELF_DIR,
                                              sys.version_info[0],
                                              sys.version_info[1]))

try:
  import bottle
  import infinit.oracles.hephaestus
  import argparse

  # Parse options
  parser = argparse.ArgumentParser(description = 'serve dynamic files')
  parser.add_argument('--host',
                      metavar = 'HOSTNAME',
                      type = str,
                      help = 'interface to listen on',
                      default = 'localhost')
  parser.add_argument('--port',
                      metavar = 'PORT',
                      type = int,
                      help = 'port to listen on',
                      default = 8000)
  infinit.oracles.hephaestus.add_options(parser)
  args = parser.parse_args()

  app = infinit.oracles.hephaestus.Hephaestus(
    **infinit.oracles.hephaestus.get_options(args)
  )

  bottle.run(app = app,
             host = args.host,
             port = args.port)
except Exception as e:
  print('%s: fatal error: %s' % (sys.argv[0], e), file = sys.stderr)
  exit(1)
