#!/usr/bin/env python3

from utils import Meta, User, HTTPException

# Get a valid session ID.
sid = None
with Meta() as meta:
  client = User(meta, 'dave.null@infinit.io')
  client.login()
  assert 'session-id' in client.cookies
  sid = client.cookies['session-id']

# Reuse check
with Meta() as meta:
  client = User(meta, 'dave.null@infinit.io')
  client.login()
  client.cookies.clear()
  try:
    print(client.get('user/self', cookies = {'session-id': sid}))
  except HTTPException as e:
    assert e.status == 403
  else:
    raise Exception('self should have raised')
