#!/usr/bin/env python3

from utils import Meta, HTTPException, User

with Meta() as meta:
  bob = User(meta, "bob@infinit.io")

  bob.login()
  barfoo = bob.post('device/create', {"name": "barfoo"})['_id']
  foobar = bob.post('device/create', {"name": "foobar"})['_id']
  # bob.logout()

  bob.post('user/connect', {"admin_token": "admintoken", "user_id": bob.id, "device_id": barfoo})
  bob.post('user/connect', {"admin_token": "admintoken", "user_id": bob.id, "device_id": foobar})
  bob.post('user/connect', {"admin_token": "admintoken", "user_id": bob.id, "device_id": foobar})

  res = meta.get('user/%s/view' % bob.id)

  assert res['success']
  assert set(res['connected_devices']) == set([foobar, barfoo])
  assert res['status']

  res = meta.post('user/disconnect', {"admin_token": "admintoken", "user_id": bob.id, "device_id": foobar})
  res = meta.post('user/disconnect', {"admin_token": "admintoken", "user_id": bob.id, "device_id": foobar})
  res = meta.post('user/disconnect', {"admin_token": "admintoken", "user_id": bob.id, "device_id": foobar})
  assert res['success']

  res = meta.get('user/%s/view' % bob.id)
  assert res['success']
  assert res['connected_devices'] == [barfoo]
  assert res['status']

  res = meta.post('user/disconnect', {"admin_token": "admintoken", "user_id": bob.id, "device_id": barfoo})
  assert res['success']

  res = meta.get('user/%s/view' % bob.id)
  assert res['success']
  assert res['connected_devices'] == []
  assert not res['status']
