#!/usr/bin/env python3

from utils import Meta, User

with Meta() as meta:
  u = User(meta, "foobar@infinit.io")
  u.login()

  peer_email = "jeanjean@infinit.io"
  res = u.post("user/invite", {"email": peer_email})

  assert res['success']
  assert meta.database.invitations.count() == 1
  invitation = meta.database.invitations.find_one()

  assert invitation["email"] == peer_email
