#!/usr/bin/env python3

from utils import Meta


with Meta() as meta:
  password = meta.create_user('foo@bar.baz')
  res = meta.post('login',
                  {
                    'device': 'android',
                    'email': 'foo@bar.baz',
                    'password': password,
                  })

  assert res['success']
  assert res['email'] == 'foo@bar.baz'
