#!/usr/bin/env python3

from utils import Meta
from infinit.oracles.meta import error

with Meta() as meta:
  res = meta.post('user/login',
                  {
                    'email': 'foo@bar.baz',
                    'device': 'android',
                    'password': 'thereisnospoon',
                  })
  assert not res['success']
  assert res['error_code'] == error.EMAIL_PASSWORD_DONT_MATCH[0]
