#!/usr/bin/env python3

from utils import Meta

with Meta() as meta:
  password = meta.create_user('foo@bar.baz')
  res = meta.post('login',
                  {
                    'device': 'android',
                    'email': 'foo@bar.baz',
                    'password': password,
                  })
  assert res['success']
  assert res['email'] == 'foo@bar.baz'
  print('=' * 10)
  res = meta.get('self')
  print(res)
  print('=' * 10)
  assert res['success']
  assert res['email'] == 'foo@bar.baz'
  res = meta.post('logout')
  assert res['success']
  res = meta.get('self')
  assert not res['success']
