#!/usr/bin/env python3

from utils import Meta


with Meta() as meta:
  res = meta.post('login',
                  {
                    'email': 'foo@bar.baz',
                    'device': 'android',
                    'password': 'thereisnospoon',
                  })
  assert not res['success']
  assert res['error_code'] == 30
