#!/usr/bin/env python3

from utils import Meta, User


with Meta() as meta:
  email = 'foobar@infinit.io'
  fullname = 'jean louis'

  u = User(meta,
           email = email,
           fullname = fullname)

  assert meta.database.users.count() == 1
  user = meta.database.users.find_one()
  assert user['email'] == email
  assert user['fullname'] == fullname
