#!/usr/bin/env python3

from utils import Meta, HTTPException

def throws(f, status):
  assert isinstance(status, int)
  try:
    f()
    assert status == 200
  except HTTPException as e:
    if status != 200:
      assert isinstance(e.status, int)
      assert e.status == status

with Meta() as meta:

  throws(lambda: meta.post('user/login', {}), 400)
  throws(lambda: meta.get('user/logout'), 200)
  throws(lambda: meta.post('user/register', {}), 400)
  throws(lambda: meta.get('user/search', {}), 400)
  throws(lambda: meta.get('user/email@email.com/view'), 200)
  throws(lambda: meta.get('user/from_public_key', {}), 400)
  throws(lambda: meta.get('user/swaggers'), 403)
  throws(lambda: meta.post('user/remove_swagger', {}), 403)
  throws(lambda: meta.post('user/favorite', {}), 403)
  throws(lambda: meta.post('user/unfavorite', {}), 403)
  throws(lambda: meta.post('user/edit', {}), 403)
  throws(lambda: meta.post('user/invite', {}), 403)
  throws(lambda: meta.post('user/admin_invite', {}), 404)
  throws(lambda: meta.get('user/invited'), 200)
  throws(lambda: meta.get('self'), 200)
  throws(lambda: meta.get('minimumself'), 200)
  throws(lambda: meta.get('user/remaining_invitations'), 200)
  # throws(lambda: meta.get('user/5241b9d226b9f10fff8be391/avatar'), 200)
  # throws(lambda: meta.post('user/5241b9d226b9f10fff8be391/avatar', {}), 200)
  throws(lambda: meta.post('debug', {}), 403)
  throws(lambda: meta.post('user/add_swagger', {}), 404)

  throws(lambda: meta.post('transaction/create', {}), 403)
  throws(lambda: meta.get('transaction/5241b9d226b9f10fff8be391/view'), 403)
  throws(lambda: meta.post('transaction/create', {}), 403)
  throws(lambda: meta.get('transactions'), 403)
  throws(lambda: meta.post('transactions', {}), 403)
  throws(lambda: meta.post('transaction/update'), 403)
  throws(lambda: meta.get('transaction/search', {}), 403)
  throws(lambda: meta.post('transaction/connect_device'), 403)
  throws(lambda: meta.post('transaction/5241b9d226b9f10fff8be391/endpoints'), 403)

  throws(lambda: meta.get('devices'), 403)
  throws(lambda: meta.get('device/<id>/view'), 403)
  throws(lambda: meta.post('device/create', {}), 403)
  throws(lambda: meta.post('device/update', {}), 403)
  throws(lambda: meta.post('device/delete', {}), 403)

  throws(lambda: meta.get('self'), 200)
  throws(lambda: meta.get('minimumself'), 200)
  throws(lambda: meta.post('debug', {}), 403)
