#!/usr/bin/env python3

from utils import Meta

with Meta() as meta:
  meta.create_user('foo@bar.baz', 'thereisnospoon')
  assert meta.database.sessions.count() == 0
  res = meta.post('login',
                  {
                    'email': 'foo@bar.baz',
                    'password': 'thereisnospoon',
                  })
  assert res['success']
  assert meta.database.sessions.count() == 1
  res = meta.post('logout')
  assert res['success']
  assert meta.database.sessions.count() == 0
