#!/usr/bin/env python3

from utils import *
from urllib.parse import quote

with Meta() as meta:
  email = 'dave.null@infinit.io'
  # Get a valid session ID.
  user = User(meta, email)
  user.login()
  assert 'session-id' in user.cookie
  id = user.cookie['session-id'].value
  # Reuse it through query string
  client = Client(meta)
  throws(lambda: client.get('user/self'), HTTPException)
  assertEq(client.get('user/self?session-id=%s' % quote(id))['email'],
           email)
  # Check it is stored as cookie
  assertEq(client.get('user/self')['email'], email)
  # Check an invalid session id is just ignored
  client.get('?session-id=')
  Client(meta).get('?session-id=lolnope')
