#!/usr/bin/env python3

from utils import Meta

url = 'http://www.google.com'
# No shortening.
with Meta(shorten_ghost_profile_url = False) as meta:
  res = meta.meta.shorten(url)
  assert res == url

# No shortening by default.
with Meta() as meta:
  res = meta.meta.shorten(url)
  assert res == url

# XXX: Write a fake shortener.
# Normal case.
# with Meta(shorten_ghost_profile_url = True,
#           enable_emails = True) as meta:
#   res = meta.meta.shorten(url)
#   assert res.startswith('http://infinit.me')

# Invalid url.
# with Meta(shorten_ghost_profile_url = True) as meta:
#   try:
#     meta.meta.shorten('@')
#     assert False
#   except AssertionError:
#     assert False
#   except BaseException as e:
#     pass
