#!/usr/bin/env python3

import os
import sys
root = os.path.dirname(__file__)
drake = os.path.abspath(os.path.join(root, '../../elle/drake/src'))
sys.path.insert(0, drake)

import drake
import drake.cxx

cxx_config = drake.cxx.Config()
cxx_config.enable_debug_symbols()
cxx_config.enable_optimization(False)
cxx_config.flag('-pthread')

with drake.Drake('../..') as d:
  d.run(
    cxx_config = cxx_config,
    python3 = None,
    qt = None,
  )
