#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

import argparse
import gap
import plasma
from pythia.constants import ADMIN_TOKEN

def ghostify(host, port, emails):
    admin = plasma.Meta(host, port)
    admin.token = ADMIN_TOKEN
    for email in emails:
      admin.ghostify(email)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("host",
                        type = str,
                        help = "The server host")

    parser.add_argument("port",
                        type = int,
                        help = "The server port")

    parser.add_argument("EMAILS",
                        nargs = '+',
                        help = "The user to ghostify")

    args = parser.parse_args()

    ghostify(args.host, args.port, set(args.EMAILS))
