#!/usr/bin/env python3

from utils import Meta, User
from uuid import uuid1

with Meta() as meta:
  bob = User(meta, 'bob@infinit.io')
  alice = User(meta, 'alice@infinit.io')
  bob.login()
  alice.login()

  tropho = uuid1()

  meta.put('trophonius/%s' % tropho, {"ip": "127.0.0.1",
                                      "port": 23456})

  meta.put('trophonius/%s/users/%s/%s' % (str(tropho), bob.id, bob.device_id))

  device = bob.device
  assert device['success']
  assert device['trophonius'] == str(tropho)

  meta.delete('trophonius/%s/users/%s/%s' % (str(tropho), bob.id, bob.device_id))

  device = bob.device
  assert device['success']
  assert device['trophonius'] == None

  meta.put('trophonius/%s/users/%s/%s' % (str(tropho), bob.id, bob.device_id))

  meta.delete('trophonius/%s' % tropho)

  device = bob.device
  assert device['success']
  assert device['trophonius'] == None
