#!/usr/bin/env python3

from utils import Meta, User
from uuid import uuid4

with Meta() as meta:
  bob = User(meta, 'bob@infinit.io')
  alice = User(meta, 'alice@infinit.io')
  bob.login()
  alice.login()

  tropho = uuid4()
  assert not bob.connected

  assert len(meta.get('trophonius')['trophonius']) == 0
  meta.put('trophonius/%s' % tropho, {"port": 23456})
  assert len(meta.get('trophonius')['trophonius']) == 1
  meta.delete('trophonius/%s' % tropho)
  assert len(meta.get('trophonius')['trophonius']) == 0
