#!/usr/bin/env python3

from utils import *


def view(as_admin):
  with Stripe() as stripe, Meta(stripe_api_key = Stripe.key, force_admin = as_admin) as meta:
    user = User(meta, 'alice@infinit.io')
    user.login()
    res = meta.get('users/' + user.id)
    assertEq('quotas' in res, as_admin)
    assertEq('plan' in res, as_admin)
    assertEq('email' in res, as_admin)
    assertEq('accounts' in res, as_admin)

    assert 'stripe' not in res
    user.put('users/%s' % user.id, {
         'plan': 'premium',
         'stripe_token': stripe.pay(user.email),
    })
    res = meta.get('users/' + user.id)
    assertEq('stripe' in res, as_admin)

view(False)
view(True)
