#!/usr/bin/env python3

from utils import Meta, User

#!/usr/bin/env python3

# Import utils first for papier and OpenSSL
from utils import Meta, User, NoOpMailer, HTTPException
from utils import assertEq, throws

from bson.objectid import ObjectId
from infinit.oracles.meta import error
from infinit.oracles.meta.server.transaction_status import CANCELED

class MailService(NoOpMailer):

  def __init__(self):
    self.keys = {}
    self.change_email = {}
    super().__init__(True)

  def template_message(self, template_message, message):
    merges = {}
    for entry in message['merge_vars'][0]['vars']:
      merges[entry['name']] = entry['content']
    if template_message == 'account-add-email':
      self.keys.update(
        {
          merges['email']: merges['key']
        })
    if template_message == 'change-email-address':
       self.change_email.update(
         {
           merges['new_email_address']: merges['hash']
         })

# Normal.
with Meta(enable_emails = True) as meta:
  import sys
  user = User(meta, 'foobar@infinit.io')
  user.login()

  meta.mailer = MailService()
  emails = ['babar@infinit.io', 'foufou@infinit.io', 'beetroot@infinit.io', 'fesse@infinit.io']
  for email in emails:
    user.put('user/accounts/%s' % email)

  assert len(meta.mailer.keys) == len(emails)
  import random
  random.shuffle(emails)
  i = 0
  for email in emails:
    user.post('users/%s/accounts/%s/confirm' % (user.email, email),
              {'key': meta.mailer.keys[email]})
    i += 1
    res = user.post('user/search_emails', {'emails': [email]})
    assert len(res['users']) == 1
    assertEq(len(user.accounts['accounts']), i + 1)
    import sys
    assert any(a['id'] == email for a in user.accounts['accounts'])
    assert res['users'][0]['id'] == user.id

# Ask for the same email.
with Meta(enable_emails = True) as meta:
  import sys
  user = User(meta, 'foobar@infinit.io')
  user.login()

  email = "endive@infinit.io"
  user.put('user/accounts/%s' % email)
  user.put('user/accounts/%s' % 'baz@infinit.io')
  user.put('user/accounts/%s' % email)

# Ask for the primary email.
with Meta(enable_emails = True) as meta:
  import sys
  user = User(meta, 'foobar@infinit.io')
  user.login()

  meta.mailer = MailService()
  try:
    user.put('user/accounts/%s' % user.email)
    assert False
  except HTTPException:
    pass

# Delete pending.
with Meta(enable_emails = True) as meta:
  import sys
  user = User(meta, 'foobar@infinit.io')
  user.login()

  # Delete an unkown email.
  throws(lambda: user.delete('user/accounts/invalid@infinit.io'))

# Delete.
with Meta(enable_emails = True) as meta:
  import sys
  user = User(meta, 'foobar@infinit.io')
  user.login()

  # Delete an unkown email.
  try:
    user.delete('user/accounts/%s' % 'invalid@infinit.io')
    assert False # It should throw.
  except HTTPException as e:
    pass

  # Add an auxiliary email and delete it.
  meta.mailer = MailService()
  email = 'endive@infinit.io'
  user.put('user/accounts/%s' % email)
  user.post('users/%s/accounts/%s/confirm' % (user.email, email),
            {'key': meta.mailer.keys[email]})
  meta.mailer.keys.clear()
  res = user.post('user/search_emails', {'emails': [email]})
  assert len(res['users']) == 1
  user.delete('user/accounts/%s' % email)
  res = user.post('user/search_emails', {'emails': [email]})
  assert len(res['users']) == 0

  # You can't delete your primary address.
  try:
    user.delete('user/accounts/%s' % user.email)
    assert False # It should throw.
  except HTTPException as e:
    pass

# Ensure you can not merged a user.
with Meta(enable_emails = True) as meta:
  import sys
  alice = User(meta, 'alice@infinit.io')
  alice.login()
  bob = User(meta, 'bob@infinit.io')
  bob.login()

  try:
    bob.put('user/accounts/%s' % alice.email)
    assert False
  except HTTPException:
    pass

  # Same if the account is created during the process.
  eve_email = 'eve@infinit.io'
  meta.mailer = MailService()
  bob.put('user/accounts/%s' % eve_email)
  assert len(meta.mailer.keys) == 1

  eve = User(meta, eve_email)
  eve.login()

  try:
    bob.post('users/%s/accounts/%s/confirm' % (bob.email, eve_email),
             {'key': meta.mailer.keys[eve_email]})
    assert False
  except HTTPException:
    pass

# Several users trying to register the same address.
with Meta(enable_emails = True) as meta:
  import sys
  alice = User(meta, 'alice@infinit.io')
  alice.login()

  bob = User(meta, 'bob@infinit.io')
  bob.login()

  email = 'endive@infinit.io'
  meta.mailer = MailService()
  bob.put('user/accounts/%s' % email)
  bob.hash = meta.mailer.keys[email]

  meta.mailer = MailService()
  alice.put('user/accounts/%s' % email)
  alice.hash = meta.mailer.keys[email]

  bob.post(
    'users/%s/accounts/%s/confirm' % (bob.email, email),
    {'key': bob.hash})
  throws(lambda:
         alice.post(
           'users/%s/accounts/%s/confirm' % (alice.email, email),
           {'key': alice.hash}))

# Swap primary email address.
with Meta(enable_emails = True) as meta:
  user = User(meta, 'foobar@infinit.io')
  user.login()
  new_email = 'endive@infinit.io'
  meta.mailer = MailService()
  user.put('user/accounts/%s' % new_email,)
  user.post('users/%s/accounts/%s/confirm' % (user.email, email),
            {'key': meta.mailer.keys[email]})
  user.logout()
  try:
    user.login(email = new_email)
    assert False
  except HTTPException:
    pass
  user.login()
  old_self = user.me
  res = user.post('user/accounts/%s/make_primary' % new_email,
                  {
                    'password': user.password
                  })
  # The user should have been kicked.
  # assert not user.logged_in
  try:
    user.login()
    assert False
  except HTTPException:
    pass
  user.login(email = new_email)

  new_self = user.me
  assert new_self['email'] == new_email
  assert new_self['identity'] != old_self['identity']
  assert new_self['public_key'] != old_self['public_key']

  # Succeed if its the same.
  user.post('user/accounts/%s/make_primary' % new_email,
            {
              'password': user.password
            })

  eve = User(meta, 'eve@infinit.io')
  eve.login()

  # You can't still the account of an other user.
  try:
    res = user.post('user/accounts/%s/make_primary' % eve.email,
                    {
                      'password': user.password
                    })
    assert False
  except HTTPException:
    pass
