#!/usr/bin/env python3

from utils import *
import requests

import infinit.oracles.meta.server.gcs
gcs_login = '798530033299-s9b7qmrc99trk8uid53giuvus1o74cif@developer.gserviceaccount.com'
gcs_key = bytes('''-----BEGIN PRIVATE KEY-----
MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBALCm3D3cHlKYRygk
vRgesY39WUGeUN/sCBsVaxMuga1bCAZ6fVoh58pQEmeBpkjaVdtB0nz9ZBVoeDtR
PcfafaUW+UFXjRf2rJ3MoJ/J72mccSD08sjVX3Q9U5iydYhjZEx3uwhUcaHG6+Rq
f4xhb/49jfFmDJ/9zCopsiPBJQgfAgMBAAECgYEAqxgByrxOdirdCGmE6D6aM+8E
qwReSnL+atT0zzBFExVPEY9Dp6+dI5soKC4vUvJ9I45+AucdL4ruoG0QTGg3NbjC
XCD88TL2UdSog/xxHAQ37EvnoPwK6v04FZHdm94eXkJMQzpf9pP8EyVEaXZWb8Uw
2MDPGluTWgkUKZitkLECQQDjuLBFwtU9rdDZB3G00P3hMXuvomPPEHRvdpvwbxLG
WX1XNPG1FlBbQhyBgUIVATn9sU28df7kANqhhnEthXY3AkEAxpaoR0rtZzPIt4c4
3PQm+mclxxEUZozrRnO/t6bDc/wGvI7C69wIu4UI8j4zFtRRuC2qCDaTorXibFRb
PKEJWQJAY8eNFUQlg30hwbbNT9kzJPU1qOOSsCwZmK1z7on8xAR6MzfzoNFCLHpv
Wx90ARgkfNCvqyBYqzbklVn/RV7xSQJBAJluCPGb+DPGFIuHU+2STRMl4lAc6BAb
TCOQhk0T8OqJi4LfIcYsqCqJLFJMsBgxTjnoPfg+gm4x7JAZ1KvRF3ECQFcwSrNV
cun1SplfUKZQZywA8ueUU/ZuGj/XXwopPR5LgWW7sgkwdCklQUPjcecWEZFy/ODl
e9FGZj7sEHpPuDE=
-----END PRIVATE KEY-----
''', 'UTF-8')

GCS_HOST = None
class GCS(infinit.oracles.meta.server.gcs.GCS):

  @property
  def host(self):
    return GCS_HOST

gcs = GCS(login = gcs_login, key = gcs_key, bucket_ns = 'test')

with Meta(gcs = gcs) as meta:
  GCS_HOST = 'http://localhost:%s/gcs' % meta.port
  import sys
  user = User(meta, 'user@infinit.io')
  user.login()
  # Upload background
  body = b'coincoin'
  content_type = 'image/png'
  content_length = len(content_type)
  response = user.put('user/backgrounds/bg.jpg',
                      raw = True,
                      content_type = content_type,
                      content_length = content_length,
                      body = body)
  assertEq(response.status_code, 301)
  url = response.headers['location']
  print('SNATHUsnthu', url)
  response = requests.put(url,
                          headers = {
                            'Content-Type': content_type,
                            'Content-Length': content_length,
                          },
                          data = body)
  assertEq(response.status_code, 204)
  # List backgrounds
  print('hop')
  assertEq(user.get('user/backgrounds')['backgrounds'], ['bg.jpg'])
  print('/hop')
  user.delete('user/backgrounds/bg.jpg')
  assertEq(user.get('user/backgrounds')['backgrounds'], [])
