#!/usr/bin/env python3

import papier

from bson.objectid import ObjectId
from utils import Meta, Trophonius, User

with Meta(force_admin = True) as meta, Trophonius(meta) as trophonius:

  u1 = User(meta, 'jeanlouis@infinit.io') # User to be deleted.
  u1.login()
  assert meta.database.sessions.count() == 1

  # Change password, wrong old_password.
  res = u1.post('user/change_password',
                {'old_password': '1' * 64, 'new_password': '1' * 64})
  assert not res['success']
  assert res['error_code'] == -213

  # Chnage password, new_password not right form.
  res = u1.post('user/change_password',
                {'old_password': '1' * 64, 'new_password': '1' * 32})
  assert not res['success']
  assert res['error_code'] == -213


  old_credentials = meta.database.users.find_one(
    {'_id': ObjectId(u1.id)},
    fields = ['password', 'identity', 'public_key']
  )

  # Change password.
  res = u1.post('user/change_password',
                {'old_password': '0' * 64, 'new_password': '1' * 64})
  assert res['success']

  try:
    u1.login()
    assert False # if we get here, we managed to login.
  except:
    pass

  new_credentials = meta.database.users.find_one(
    {'_id': ObjectId(u1.id)},
    fields = ['password', 'identity', 'public_key']
  )

  assert new_credentials['password'] != old_credentials['password']
  assert new_credentials['public_key'] != old_credentials['public_key']
  assert new_credentials['identity'] != old_credentials['identity']

  assert new_credentials['password'] == 'cb1263e961cc62899c4ae127a692aa0c'

  u1.login(password = '1' * 64)
