#!/usr/bin/env python3

import papier

from bson.objectid import ObjectId
from utils import Meta, Trophonius, User

with Meta(force_admin = True) as meta, Trophonius(meta) as trophonius:

  u1 = User(meta, 'jeanlouis@infinit.io') # User to be deleted.
  u1.login()
  assert meta.database.sessions.count() == 1

  # Change password, wrong old_password.
  res = u1.post('user/change_password',
                {'old_password': '1' * 64, 'new_password': '1' * 64})
  assert not res['success']
  assert res['error_code'] == -213

  # Chnage password, new_password not right form.
  res = u1.post('user/change_password',
                {'old_password': '1' * 64, 'new_password': '1' * 32})
  assert not res['success']
  assert res['error_code'] == -213

  # Change password.
  res = u1.post('user/change_password',
                {'old_password': '0' * 64, 'new_password': '1' * 64})
  assert res['success']

  db_password = meta.database.users.find_one(
    {'_id': ObjectId(u1.id)},
    fields = ['password']
  )['password']
  assert db_password == 'cb1263e961cc62899c4ae127a692aa0c'
