#!/usr/bin/env python3

import datetime

from utils import *
from infinit.oracles.meta import error

unconfirmed_email_leeway = 100

with Meta() as meta:
  bob = User(meta)
  bob.login()
  res = bob.get('user/email_subscriptions')
  assert res['tips']
  assert res['alerts']
  res = bob.post('user/email_subscriptions',
                 {'tips': False})
  assert not res['tips']
  subscriptions = bob.get('user/email_subscriptions')
  assertEq(subscriptions, {'tips': False, 'alerts': True,})
