#!/usr/bin/env python3

from utils import Meta, User

with Meta() as meta:
  u1 = User(meta, "foobar@infinit.io")
  u2 = User(meta, "barfoo@infinit.io")

  u1.login()
  res = u1.post('user/favorite', {'user_id': u2.id})

  assert res['success']
  assert u1.favorites == [u2.id]

  res = u1.post('user/unfavorite', {'user_id': u2.id})

  assert res['success']
  assert u1.favorites == []
