#!/usr/bin/env python3

from utils import Meta

with Meta() as meta:
  email = 'foobar@infinit.io'

  res = meta.post('user/admin_invite', {"email": email, "admin_token": "admintoken"})
  assert res['success']
  assert meta.database.invitations.count() == 1
  invitation = meta.database.invitations.find_one()
