#!/usr/bin/env python3

import datetime

from utils import Meta, User, throws
import infinit.oracles.meta.server.transaction_status as transaction_status

import bson

with Meta(stripe_api_key = 'sk_test_WtXpwiieEsemLlqrQeKK0qfI') as meta:
  alice = User(meta, "alice@infinit.io")
  alice.login()
  alice.put('user/invite', {'name': 'bob@infinit.io'})
  inv = alice.get('user/invites')
  inv = inv['results']
  assert len(inv) == 1
  assert inv[0]['status'] == 'pending'
  bob = User(meta, 'bob@infinit.io')
  bob.login()
  inv = alice.get('user/invites')
  inv = inv['results']
  assert len(inv) == 1
  assert inv[0]['status'] == 'completed'

  alice.put('user/invite', {'name': 'carl@infinit.io'})
  carl = User(meta, 'carl2@infinit.io')
  carl.login()
  gc = meta.database.users.find_one({'accounts.id': 'carl@infinit.io'})['ghost_code']
  carl.post('ghost/%s/merge' % gc)
  inv = alice.get('user/invites')
  inv = inv['results']
  assert len(inv) == 2
  assert inv[0]['status'] == 'completed'
  assert inv[1]['status'] == 'completed'