#!/usr/bin/env python3

from utils import Meta, HTTPException, User

with Meta() as meta:
  bob = User(meta, 'bob@infinit.io')
  bob.login()
  res = bob.get('user/login-token')
  assert len(res['login-token'])
  bob.logout()
  try:
    bob.get('user/login-token')
    assert False # should throw as bob is not logged in.
  except:
    pass
