#!/usr/bin/env python3
from time import time
from utils import Meta, User
from uuid import uuid4

with Meta() as meta:
  user = User(meta, 'foo@bar.baz')
  user.login()
  import sys
  print(user.data, file = sys.stderr)
  assert not user.data['connected']
