#!/usr/bin/env python3

from utils import Meta, User
from uuid import uuid4

with Meta() as meta:
  bob = User(meta, "bob@infinit.io")

  bob.login()
  device_id = bob.device['_id']
  device_name = bob.device['name']
  bob.logout()

  new_device_id = uuid4()
  bob.login(device_id = str(new_device_id))
  assert str(new_device_id) == bob.device['_id']
  bob.logout()

  # Device name is the same.
  bob.login(device_id = device_id)
  assert device_name == bob.device['name']
  bob.logout()
