#!/usr/bin/env python3

from utils import Meta
from uuid import uuid4

with Meta() as meta:
  password = meta.create_user('foo@bar.baz')
  res = meta.post('user/login',
                  {
                    'device_id' : str(uuid4()),
                    'email': 'foo@bar.baz',
                    'password': password,
                  })

  assert res['success']
  assert res['email'] == 'foo@bar.baz'
