#!/usr/bin/env python3

from utils import Meta, User

with Meta() as meta:
  bob = User(meta, "bob@infinit.io")

  bob.  login()
  device_id = bob.device['_id']
  device_name = bob.device['name']
  bob.logout()

  bob.login(device_id = device_id)
  assert device_id == bob.device['_id']
  bob.logout()

  # Device name is the same.
  bob.login()
  assert device_name == bob.device['name']
  bob.logout()

  res = bob.login(device_name = "foobarbaz")
  assert device_id != bob.device["_id"]
  foobarbaz = bob.device
  bob.logout()

  bob.login(device_name = device_name)
  assert device_id == bob.device["_id"]
  bob.logout()
