#!/usr/bin/env python3

import utils
from infinit.oracles.meta import error
from uuid import uuid4

with utils.Meta() as meta:
  try:
    meta.post('login',
              {
                'email': 'foo@bar.baz',
                'device_id': str(uuid4()),
                'password': 'thereisnospoon',
              })
  except utils.HTTPException as e:
    assert e.status == 403
    assert e.content['code'] == error.EMAIL_PASSWORD_DONT_MATCH[0]
  else:
    raise Exception('invalid login should have yield 403 forbidden')
