#!/usr/bin/env python3

from utils import Meta, HTTPException

with Meta() as meta:
  password = meta.create_user('foo@bar.baz')
  res = meta.post('user/login',
                  {
                    'device_name': 'android',
                    'email': 'foo@bar.baz',
                    'password': password,
                  })
  assert res['success']
  assert res['email'] == 'foo@bar.baz'
  res = meta.get('self')
  assert res['success']
  assert res['email'] == 'foo@bar.baz'
  res = meta.post('user/logout')
  assert res['success']
  try:
    res = meta.get('self')
  except HTTPException as e:
    assert e.status == 403
