#!/usr/bin/env python3

from utils import *
from pprint import pprint

from bson.objectid import ObjectId
from infinit.oracles.meta import error
from infinit.oracles.meta.server.transaction_status import CANCELED

from infinit.oracles.notification import notifications
for name, value in notifications.items():
  globals()[name.upper()] = value

from infinit.oracles.meta.server.transaction_status import INITIALIZED, ACCEPTED, FINISHED, GHOST_UPLOADED

class MailService(NoOpMailer):

  def __init__(self):
    self.codes = {}
    super().__init__(True)

  def template_message(self, template_message, message):
    merges = {}
    for entry in message['merge_vars'][0]['vars']:
      merges[entry['name']] = entry['content']
    if template_message == 'send-file-url':
      self.codes.update(
        {
          merges['sendername']: merges['ghost_code']
        })

# Normal.
with Meta(enable_emails = True,
          shorten_ghost_profile_url = False) as meta:
  alice = User(meta, 'alice@infinit.io')
  alice.login()
  bob = User(meta, 'bob@infinit.io')
  # Spoiler: Eve is bob...
  eve = 'eve@infinit.io'
  alice.sendfile(eve)
  bob.login()
  assert bob.get('users/%s' % eve)['register_status'] == 'ghost'
  bob.put('user/accounts/%s' % eve)
  emails = meta.emailer.emails
  assertEq(len(emails), 1)
  bob.post('users/%s/accounts/%s/confirm' % (bob.id, eve),
           {'confirm_token': emails[0].variables['confirm_token']})
  # Spoiler: Eve is bob...
  assert bob.get('users/%s' % eve)['register_status'] == 'ok'
  assert bob.id == bob.get('users/%s' % eve)['id']
  assert len(bob.swaggers) == 1
  assert bob.swaggers[0] == alice.id

# Try to merge an existing user.
with Meta(enable_emails = True) as meta:
  alice = User(meta, 'alice@infinit.io')
  alice.login()
  bob = User(meta, 'bob@infinit.io')
  try:
    bob.post('user/accounts/email/add', {'email': alice.email})
    assert False
  except HTTPException:
    pass

  try:
    bob.post('user/accounts/email/add', {'email': bob.email})
    assert False
  except HTTPException:
    pass

  eve = 'eve@infinit.io'
  alice.sendfile(eve)
  bob.login()
  bob.put('user/accounts/%s' % eve)
  # But eve registers...
  print('XXX', meta.emailer.emails)
  eve = User(meta, eve)
  throws(lambda:
         bob.post(
           'users/%s/accounts/%s/confirm' % (bob.id, eve.email),
           {'confirm_token': eve.email_confirmation_token}),
         HTTPException)

# Notifications.
with Meta(enable_emails = True) as meta:
  with Trophonius(meta) as trophonius:
    alice = User(meta, 'alice@infinit.io')
    alice.login(trophonius = trophonius)
    bob = User(meta, 'bob@infinit.io')
    bob.login(trophonius = trophonius)

    trophonius.connect_user(alice)
    trophonius.connect_user(bob)

    email = 'navet@infinit.io'
    alice.sendfile(email)

    assert alice.next_notification().type == NEW_SWAGGER

    meta.mailer = MailService()
    bob.put('user/accounts/%s' % email)
    emails = meta.emailer.emails
    assertEq(len(emails), 1)
    bob.post('users/%s/accounts/%s/confirm' % (bob.id, email),
             {'confirm_token': emails[0].variables['confirm_token']})

    trophonius.poll()
    assert len(bob.notifications) == 1
    assert bob.next_notification().type == NEW_SWAGGER

    # Ghost is now bob.
    assert alice.next_notification().type == DELETED_SWAGGER
    assert alice.next_notification().type == NEW_SWAGGER

    email = 'poireau@infinit.io'
    tr, _ = alice.sendfile(email)
    alice.transaction_update(tr['_id'], INITIALIZED)
    # Ghost is a new swagger.
    assert alice.next_notification().type == NEW_SWAGGER
    # Transaction notification.
    assert alice.next_notification().type == PEER_TRANSACTION

    assert len(bob.notifications) == 0
    assert len(bob.transactions) == 0
    meta.mailer = MailService()
    bob.put('user/accounts/%s' % email)
    emails = meta.emailer.emails
    assertEq(len(emails), 1)
    bob.post('users/%s/accounts/%s/confirm' % (bob.id, email),
             {'confirm_token': emails[0].variables['confirm_token']})

    assert len(bob.transactions) == 1
    # Alice is a bob new swagger.
    # assert bob.next_notification().type == NEW_SWAGGER
    # Bob get the notification for the ghost transaction.
    # notif = bob.next_notification()
    # assert notif.type == PEER_TRANSACTION
    # assert notif.status == INITIALIZED
    # assert notif.sender_id == alice.id

    # Ownership changed.
    # Fake trophonius is not deterministic...
    # alices_notifications = [alice.next_notification().type,
    #                         alice.next_notification().type,
    #                         alice.next_notification().type]
    # alices_notifications.sort()
    # expected_notifications = [PEER_TRANSACTION, DELETED_SWAGGER, NEW_SWAGGER]
    # expected_notifications.sort()
    # assert alices_notifications == expected_notifications
    # assert len(alice.notifications) == 0

    # # Check if bob can update transaction and get the notifications
    # bob.transaction_update(tr['_id'], ACCEPTED)

    # notif = alice.next_notification()
    # assert notif.type == PEER_TRANSACTION

    # assert notif.status == ACCEPTED
    # notif = bob.next_notification()
    # assert notif.type == PEER_TRANSACTION
    # assert notif.status == ACCEPTED

    # bob.transaction_update(tr['_id'], FINISHED)

    # notif = alice.next_notification()
    # assert notif.type == PEER_TRANSACTION
    # assert notif.status == FINISHED
    # notif = bob.next_notification()
    # assert notif.type == PEER_TRANSACTION
    # assert notif.status == FINISHED

# Check code.
with Meta(enable_emails = True) as meta:
  alice = User(meta, 'alice@infinit.io')
  alice.login()
  bob = User(meta, 'bob@infinit.io')
  eve = 'eve@infinit.io'
  meta.mailer = MailService()
  tr, _ = alice.sendfile(eve, initialize = True)
  alice.transaction_update(tr['_id'], GHOST_UPLOADED)
  bob.login()
  assert bob.get('users/%s' % eve)['register_status'] == 'ghost'
  eve_id = bob.get('users/%s' % eve)['id']
  emails = meta.emailer.template('Transfer (Initial)')
  code = emails[0].variables['ghost_code']
  throws(lambda: meta.get('ghost/code/00000'), 404)
  bob.post('ghost/%s/merge' % code)
  throws(lambda: meta.get('ghost/code/%s' % code), 404)

# Using code.
with Meta(enable_emails = True) as meta:
  alice = User(meta, 'alice@infinit.io')
  alice.login()
  luc = User(meta, 'luc@infinit.io')
  luc.login()
  bob = User(meta, 'bob@infinit.io')
  # Spoiler: Eve is bob...
  eve = 'eve@infinit.io'
  meta.mailer = MailService()
  tr, _ = alice.sendfile(eve, initialize = True)
  alice.transaction_update(tr['_id'], GHOST_UPLOADED)
  tr, _ = luc.sendfile(eve, initialize = True)
  luc.transaction_update(tr['_id'], GHOST_UPLOADED)
  bob.login()
  assert bob.get('users/%s' % eve)['register_status'] == 'ghost'
  eve_id = bob.get('users/%s' % eve)['id']
  emails = meta.emailer.template('Transfer (Initial)')
  codes = {}
  for email in emails:
    assertEq(email.template, 'Transfer (Initial)')
    codes[email.variables['sender']['fullname']] = \
      email.variables['ghost_code']
  assertEq(len(codes), 2)
  assertEq(codes[alice.fullname], codes[luc.fullname])
  code = codes[alice.fullname]
  assert len(bob.transactions) == 0
  bob.post('ghost/%s/merge' % code, {})
  assert bob.get('users/%s' % eve_id)['register_status'] == 'merged'
  bob.synchronize(init = True)
  assert len(bob.transactions) == 2
  assert len(bob.swaggers) == 2
  try:
    bob.post('user/merge/%s' % code, {})
  except HTTPException as e:
    pass
