#!/usr/bin/env python3

from utils import *

# Fetch referral code.
with Meta() as meta:
  bob = User(meta, 'bob@infinit.io')
  bob.login()
  res = bob.get('user/referral-code')
  # ObjectId is 12 bytes, base64 gives 4/3 n
  assertEq(len(res['referral_code']), 16)

# Add referral code retrospectively.
with Meta() as meta:

  def __quota_for_user(user):
    if not user.logged_in:
      user.login()
    return user.me['quotas']['links']['quota']

  plan = meta.database.plans.find_one({'name': 'basic'})
  default_storage = plan['quotas']['links']['default_storage']
  referrer_bonus = plan['quotas']['links']['bonuses']['referrer']
  referree_bonus = plan['quotas']['links']['bonuses']['referree']
  bob = User(meta, 'bob@infinit.io')
  bob.login()
  res = bob.get('user/referral-code')
  assertEq(len(res['referral_code']), 16)
  assertEq(res['refer_count'], 0)
  bob_quota_1 = __quota_for_user(bob)
  assertEq(bob_quota_1, default_storage)
  alice = User(meta, 'alice@infinit.io')
  alice.login()
  alice_quota_1 = __quota_for_user(alice)
  assertEq(alice_quota_1, default_storage)
  alice.post('user/referral-code',
             {'referral_code': res['referral_code']})
  bob_quota_2 = __quota_for_user(bob)
  assertEq(bob_quota_2,
           (bob_quota_1 + referrer_bonus))
  alice_quota_2 = __quota_for_user(alice)
  assertEq(alice_quota_2,
           (alice_quota_1 + referree_bonus))
  res = bob.get('user/referral-code')
  assertEq(res['refer_count'], 1)
  res = bob.get('user/invites')
  assertEq(res['referred'],
           [{'name': 'alice', 'id': str(alice.id)}])

# Add referral code retrospectively failure checks.
with Meta() as meta:
  bob = User(meta, 'bob@infinit.io')
  bob.login()
  referral_code = bob.get('user/referral-code')['referral_code']
  alice = User(meta, 'alice@infinit.io')
  # Not logged in
  try:
    alice.post('user/referral-code', {'referral_code': referral_code})
    assert False
  except HTTPException as e:
    assert e.status == 403
  alice.login()
  # Wrong code
  throws(lambda: alice.post('user/referral-code', {'referral_code': 'wrongcode'}))
  # Too old account
  import datetime
  date = datetime.datetime.utcnow() - datetime.timedelta(days = 10)
  meta.database.users.update(
    {'_id': alice._id},
    {'$set': {'creation_time': date}})
  try:
    alice.post('user/referral-code', {'referral_code': referral_code})
    assert False
  except HTTPException as e:
    assert e.status == 403
