#!/usr/bin/env python3

from utils import *
from uuid import uuid4

with Meta() as meta:
  alice_email = "alice@infinit.io"
  bob = User(meta, "bob@infinit.io")
  bob.login()
  transaction, res = bob.sendfile(recipient = alice_email)
  assert res['success']
  transaction_id = res['created_transaction_id']
  ghost = meta.get('users/%s' % alice_email)
  expected_fullname = "alice in chains"
  alice = User(meta, alice_email, fullname = expected_fullname)
  alice.login()
  assert alice.fullname == expected_fullname

# Check code.
with Meta() as meta, Trophonius(meta) as wtropho:
  _alice = {'email': 'alice@infinit.io', 'password': '1' * 64}
  _bob = {'email': 'bob@infinit.io', 'password': '0' * 64}
  bob = Client(meta)
  res = bob.post('user/register',
    {
      'email': _bob['email'],
      'password': _bob['password'],
      'fullname': 'bob'
    })
  assert 'ghost_code' not in res
  bob.post('login', {'email': _bob['email'], 'password': _bob['password'], 'device_id': str(uuid4())})
  User.sendfile(bob, recipient = 'alice@infinit.io', device_id = str(uuid4()), initialize = True)

  alice = Client(meta)
  res = alice.post('user/register',
    {
      'email': _alice['email'],
      'password': _alice['password'],
      'fullname': 'alice'
    })
  assert 'ghost_code' in res
