#!/usr/bin/env python3

from utils import *

with Meta(enable_emails = True) as meta:
  email = 'foobar@infinit.io'
  fullname = 'jean louis'

  u = User(meta,
           email = email,
           fullname = fullname)
  assert meta.invitation.subscribed(email)
  assert meta.database.users.count() == 1
  user = meta.database.users.find_one()
  assert user['email'] == email
  assert user['fullname'] == fullname
  assert 'source' not in user.keys()
  assert 'creation_time' in user

# Check that register source is saved.
with Meta() as meta:
  email = 'jeantest@infinit.io'
  fullname = 'Jean Test'

  u = User(meta,
           email = email,
           fullname = fullname,
           source = 'test')
  assert meta.invitation.subscribed(email)
  assert meta.database.users.count() == 1
  user = meta.database.users.find_one()
  assert user['email'] == email
  assert user['fullname'] == fullname
  assert user['source'] == 'test'
  assert 'creation_time' in user

# Check that null passwords are rejected.
with Meta() as meta:
  email = 'jeantest@infinit.io'
  fullname = 'Jean Test'
  try:
    meta.post('user/register', {
      'email': email,
      'fullname': fullname,
      'password': None}
    )
    assert False
  except HTTPException as e:
    assert e.status == 400
    pass

# Check that password is needed.
with Meta() as meta:
  email = 'jeantest@infinit.io'
  fullname = 'Jean Test'
  try:
    meta.post('user/register', {
      'email': email,
      'fullname': fullname
    })
    assert False
  except HTTPException as e:
    assert e.status == 400
    pass

# Referral code test.
with Meta() as meta:
  u1 = User(meta,
            email = 'jeantest@infinit.io',
            fullname = 'Jean Test')
  u1.login()
  res = u1.get('user/referral-code')
  referral_code = res['referral_code']
  assert len(referral_code)
  assert (res['refer_count'] == 0)
  initial_quota = meta.database.users.find_one(
    {'_id': u1._id}, {'quota': True})['quota']
  assert (initial_quota['total_link_size'] == 1e9)
  u2 = User(meta,
            email = 'jeanprofite@infinit.io',
            fullname = 'Jean Profite',
            referral_code = referral_code)
  res = u1.get('user/referral-code')
  assert (res['refer_count'] == 1)
  u2.login()
  referrer_quota = meta.database.users.find_one(
    {'_id': u1._id}, {'quota': True})['quota']
  assertEq(referrer_quota['total_link_size'],
           initial_quota['total_link_size'] + 1e9)
  referree_quota = meta.database.users.find_one(
    {'_id': u2._id}, {'quota': True})['quota']
  assertEq(referree_quota['total_link_size'],
           initial_quota['total_link_size'] + 500e6)
  u3 = User(meta,
            email = 'wrongcode@infinit.io',
            referral_code = 'wrong')
