#!/usr/bin/env python3

from utils import Meta, Client, HTTPException, User
from uuid import uuid4
from bson import ObjectId
import copy

with Meta() as meta:
  password = meta.create_user('foo@bar.baz')
  user = {
    'email': 'foo@bar.baz',
    'password': password,
    'pick_trophonius': False,
  }

  user_device_0 = copy.deepcopy(user)
  user_device_0['device_id'] = str(uuid4())

  user_device_1 = copy.deepcopy(user)
  user_device_1['device_id'] = str(uuid4())

  # Login a user on device 0.
  client0 = Client(meta)
  assert meta.database.sessions.count() == 0
  res = client0.post('login', user_device_0)
  assert res['success']
  res = client0.get('user/self')
  assert meta.database.sessions.count() == 1

  # Login the same user but on a different device (1).
  client1 = Client(meta)
  res = client1.post('login', user_device_1)
  assert res['success']
  res = client1.get('user/self')
  assert meta.database.sessions.count() == 2

  # Logout user 0.
  res = client0.post('logout')
  assert res['success']
  assert meta.database.sessions.count() == 1

  # Relogout user 0.
  try:
    res = client0.post('logout')
    raise Exception("shouldn't be logged in anymore")
  except HTTPException as e:
    pass
  assert meta.database.sessions.count() == 1

  # Relog user on device 0.
  res = client0.post('login', user_device_0)
  assert res['success']
  res = client0.get('user/self')
  assert meta.database.sessions.count() == 2

  # Logout user on device 1.
  res = client1.post('logout')
  assert res['success']
  assert meta.database.sessions.count() == 1

  # Logout user on device 0.
  res = client0.post('logout')
  assert res['success']
  assert meta.database.sessions.count() == 0


# Session migration.
with Meta(enable_emails = True) as meta:
  user = User(meta, 'foobar@infinit.io')
  user.login()
  assert meta.database.sessions.count() == 1
  # Modify the current session to the old pattern.
  meta.database.sessions.find_and_modify(
    {
      'identifier': ObjectId(user.id)
    },
    {
      '$unset': {'identifier': 1},
      '$set': {'email': user.email},
    })
  assert 'email' in meta.database.sessions.find_one()
  assert 'identifier' not in meta.database.sessions.find_one()

  user.me

  user.logout()
  assert meta.database.sessions.count() == 0
