#!/usr/bin/env python3

from utils import Meta, Client, User

with Meta(force_admin = True) as meta:
  u1 = User(meta, 'jeanlouis@infinit.io')
  u2 = User(meta, 'pascal@infinit.io')

  res = meta.post('user/add_swagger',
                  {'user1': u1.id,
                   'user2': u2.id})
  assert res['success']

  res1 = u1.login()
  res2 = u2.login()

  assert len(res1['swaggers']) == 1
  assert len(res2['swaggers']) == 1

  assert len(u1.swaggers) == 1
  assert len(u2.swaggers) == 1

  assert u1.id in u2.swaggers
  assert u2.id in u1.swaggers

  assert len(u1.get('user/full_swaggers')['swaggers']) == 1
  assert len(u2.get('user/full_swaggers')['swaggers']) == 1
