#!/usr/bin/env python3

from utils import Meta, User

with Meta() as meta:
    user = User(meta, "foobar@infinit.io")
    user.login()
    plan = 'basic'
    user.put('users/%s' % user.id, {'plan': plan})
    res = user.data
    assert res['plan'] == plan
