#!/usr/bin/env python3

from utils import *

with Meta() as meta:
  bob = User(meta, email = 'bobbymcferrin@infinit.com', fullname = 'jean @ bob')
  bob.login()
  alices = []
  number_of_alices = 8
  emails = []
  for i in range(0, number_of_alices):
    email = ('alice%s@infinit.com' % i)
    alices.append(User(meta, email))
    emails.append(email)
  res = bob.post('user/search_emails?limit=10&offset=0', {'emails': emails})
  assert len(res['users']) == 8
  for user in res['users']:
    # assert 'connected' in user
    assert 'connected_devices' in user
  bob.logout()
