#!/usr/bin/env python3

from utils import HTTPException, Meta, User

with Meta() as meta:
  alice = User(meta, 'alice@provider.com')
  bob = User(meta, 'bob@provider.com')
  charles = User(meta, 'charles@provider.com')
  res = meta.get('user/search?text=al')
  assert res['users'] == [alice.id]
  res = meta.get('user/search?text=dick')
  assert res['users'] == []
