#!/usr/bin/env python3

from utils import HTTPException, Meta, User

with Meta() as meta:
  alice = User(meta, 'alice@provider.com')
  bob = User(meta, 'bob@provider.com')
  charles = User(meta, 'charles@provider.com')
  alice.login();
  res = alice.get('users?search=al')
  assert res['users'][0]['id'] == alice.id
  res = alice.get('users?search=dick')
  assert res['users'] == []
  alice.logout()

with Meta() as meta:
  alices = []
  number_of_alices = 8
  for i in range(0, number_of_alices):
    alices.append(User(meta, 'alice%s@infinit.com' % i))
  bob = User(meta, 'bob@infinit.com')

  bob.login()

  res = bob.get('users?search=al&limit=10')
  assert len(res['users']) == number_of_alices

  bob.sendfile(alices[3].email)
  bob.sendfile(alices[3].email)
  bob.sendfile(alices[3].email)
  bob.sendfile(alices[5].email)
  bob.sendfile(alices[5].email)
  bob.sendfile(alices[1].email)

  # Current swag amounts:
  # alice3 : 3
  # alice5 : 2.
  # alice1 : 1.

  res = bob.get('users?search=al&limit=10')
  assert len(res['users']) == number_of_alices
  assert res['users'][0]['id'] == alices[3].id
  assert res['users'][1]['id'] == alices[5].id
  assert res['users'][2]['id'] == alices[1].id

with Meta() as meta:
  bob = User(meta, email = 'bob@infinit.com', fullname = 'jean @ bob')

  bob.login()
  res = bob.get('users?search=jean%20@&limit=10')
  assert len(res['users']) == 1

  bob.login()
