#!/usr/bin/env python3

from utils import Meta, User, HTTPException

with Meta() as meta:
  u1 = User(meta, 'foobar@infinit.io')

  res = meta.get('users/%s' % u1.id)
  assert res['id'] == u1.id

  res = meta.get('users/%s' % u1.email)
  assert res['id'] == u1.id

  try:
    meta.get('users/invalid-id')
  except HTTPException as e:
    assert e.status == 404
