#!/usr/bin/env python3

from utils import Meta, User

with Meta() as meta:
  u1 = User(meta, "foobar@infinit.io")

  res = meta.get('user/%s/view' % u1.id)
  assert res['success']

  res = meta.get('user/%s/view' % u1.email)
  assert res['success']
