#!/usr/bin/env sh
# Copyright (c) 2012, PICHOT Fabien Paul Leonard <pichot.fabien@gmail.com>
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
# IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

infinit_env_show() {
  for i in $(env | egrep '(INFINIT|ELLE)')
  do
    i8info $i
  done
}

infinit_clean() {
    for mountpoint in $(sudo mount -t fuse.infinit | cut -d " " -f 3)
    do
        i8info unmount $mountpoint
        fusermount -u $mountpoint
    done
}

infinit_home_clean() {
    rm -rf ~/.infinit/*
}

infinit_switch_dev() {
	export INFINIT_META_HOST=development.infinit.io
	export INFINIT_LONGINUS_HOST=development.infinit.io
	export INFINIT_TROPHONIUS_HOST=development.infinit.io
}

infinit_switch_prod() {
	export INFINIT_META_HOST=production.infinit.io
	export INFINIT_LONGINUS_HOST=production.infinit.io
	export INFINIT_TROPHONIUS_HOST=production.infinit.io
}

infinit_longinus() {
  case $1 in
    host)
      export INFINIT_META_HOST=$2
      ;;
    port)
      export INFINIT_META_PORT=$2
      ;;
    *)
      i8error invalid argument $1
      ;;
   esac
}

infinit_trophonius() {
  case $1 in
    host)
      export INFINIT_META_HOST=$2
      ;;
    port)
      export INFINIT_META_PORT=$2
      ;;
    *)
      i8error invalid argument $1
      ;;
   esac
}
infinit_meta() {
  case $1 in
    host)
      export INFINIT_META_HOST=$2
      ;;
    port)
      export INFINIT_META_PORT=$2
      ;;
    *)
      i8error invalid argument $1
      ;;
   esac
}
