#!/usr/bin/env python3

from utils import Meta, User
from infinit.oracles.meta.server.mail import Mailer

class MailService(Mailer):

  def __init__(self, sender_fullname, expected_template):
    super().__init__(True)
    self.__sender = sender_fullname
    self.__expected_template = expected_template
    self.__sent = False

  # Override Mailer private __send method.
  def _Mailer__send(self, msg):
    # For some reason, It's impossible to search inside.
    # assert str(msg).find("%s_wants_to_share" % self.__sender) > 0
    # assert str(msg).find(self.__expected_template) > 0
    self.__sent = True

  @property
  def sent(self):
    return self.__sent

with Meta() as meta:
  alice = User(meta, "alice@infinit.io")
  bob = User(meta, "bob@infinit.io")

  response = {"email": "alice@infinit.io"}

  bob.login()

  transaction, res = bob.sendfile(recipient_id = alice.id)
  assert res['success']

  transaction_id = res['created_transaction_id']

  alice.login()

  res = alice.get('transaction/%s/view' % transaction_id)

  for key in transaction.keys():
    if key in ['id_or_email', 'device_id']: # Special cases.
      continue
    assert res[key] == transaction[key]
  res['recipient_id'] == transaction['id_or_email']

# Invited by email.
with Meta(enable_emails = True) as meta:
  alice_email = "alice@infinit.io"
  bob = User(meta, "bob@infinit.io")

  bob.login()
  meta.mailer = MailService(bob.fullname, 'send-file')

  transaction, res = bob.sendfile(recipient_id = alice_email)
  assert res['success']

  assert meta.mailer.sent
  transaction_id = res['created_transaction_id']

  alice = User(meta, alice_email)
  alice.login()

  res = alice.get('transaction/%s/view' % transaction_id)

  for key in transaction.keys():
    if key in ['id_or_email', 'device_id']: # Special cases.
      continue
    assert res[key] == transaction[key]
  res['recipient_id'] == transaction['id_or_email']
