#!/usr/bin/env python3


from utils import Meta, User

import bson

from infinit.oracles.meta.server.transaction_status import \
  ACCEPTED as accepted, \
  FINISHED as finished, \
  INITIALIZED as initialized

with Meta() as meta:
  alice = User(meta, 'alice@infinit.io')
  alice.login()
  bob = User(meta, 'bob@infinit.io')
  bob.login()
  i = bson.ObjectId(alice.id)
  assert 'transactions' not in meta.database.users.find_one({'_id': i})
  # Send to a peer.
  transaction, res = alice.sendfile(recipient_id = 'bob@infinit.io',
                                    initialize = True)
  # Send to a peer and accept.
  transaction, res = alice.sendfile(recipient_id = 'bob@infinit.io',
                                    initialize = True)
  bob.transaction_update(res['created_transaction_id'], accepted)
  # Send to a peer and download.
  transaction, res = alice.sendfile(recipient_id = 'bob@infinit.io',
                                    initialize = True)
  bob.transaction_update(res['created_transaction_id'], accepted)
  bob.transaction_update(res['created_transaction_id'], finished)
  # Send to a ghost
  alice.sendfile(recipient_id = 'carol@infinit.io')
  # Send to a ghost and download
  transaction, res = alice.sendfile(recipient_id = 'carol@infinit.io',
                                    initialize = True)
  alice.post('transactions/%s/downloaded?key=admin' \
             % res['created_transaction_id'])
  # Download a transaction
  transaction, res = bob.sendfile(recipient_id = 'alice@infinit.io',
                                  initialize = True)
  alice.transaction_update(res['created_transaction_id'], accepted)
  alice.transaction_update(res['created_transaction_id'], finished)
  # Leave a pending transaction
  bob.sendfile(recipient_id = 'alice@infinit.io', initialize = True)
  # Create a link
  link = alice.post('link',
                    {
                      'files': ['lol'],
                      'name': 'lol.zip',
                      'message': '',
                    })
  # Create a clicked link
  res = alice.post('link',
                   {
                     'files': ['lol'],
                     'name': 'lol.zip',
                     'message': '',
                   })
  alice.get('link/%s' % res['transaction']['hash'])
  # Check counters
  transactions = meta.database.users.find_one({'_id': i})['transactions']
  print(transactions)
  assert transactions['reached'] == 3
  assert transactions['reached_link'] == 1
  assert transactions['reached_peer'] == 2
  assert transactions['received'] == 1
  assert transactions['received_peer'] == 1
  assert transactions['sent'] == 7
  assert transactions['sent_link'] == 2
  assert transactions['sent_peer'] == 5
