#!/usr/bin/env python3

from utils import Meta, User

with Meta() as meta:
  bob = User(meta, "bob@infinit.io")
  bob.login()
  transaction, res = bob.sendfile(recipient = "alice@infinit.io", use_identifier = False)
  assert res['success']

  transaction_id = res['created_transaction_id']

  alice = User(meta, "alice@infinit.io")
  alice.login()

  res = alice.get('transaction/%s' % transaction_id)

  for key in transaction.keys():
    if key in ['id_or_email', 'device_id']: # Special cases.
      continue
    assert res[key] == transaction[key]
  res['recipient_id'] == transaction['id_or_email']
