#!/usr/bin/env python3

from utils import *
from infinit.oracles.meta.server import transaction_status

from infinit.oracles.notification import notifications
for name, value in notifications.items():
  globals()[name.upper()] = value

class Metrics:

  def __init__(self):
    self.got = {}

  def send(self, metrics, collection, user_agent = None):
    for metric in metrics:
      self.got.setdefault(metric['event'], []).append(metric)

with Meta() as meta:
  assert meta.meta.metrics is None
  bob = User(meta, 'bob@infinit.io')
  bob.login()
  transaction, res = bob.send(recipient = 'alice@infinit.io')
  transaction_id = res['created_transaction_id']
  bob.transaction_update(transaction_id,
                         transaction_status.GHOST_UPLOADED)
  emails = meta.emailer.template('Transfer (Initial)')
  assertEq(len(emails), 1)
  email = emails[0]
  t = meta.get(
    'transactions/%s?key=%s' % (
      transaction_id,
      email.variables['transaction']['key']))
  assertEq(t['id'], transaction_id)

  alice = User(meta, 'alice@infinit.io')
  alice.login()

  t = alice.get('transaction/%s' % transaction_id)
  assertEq(t['id'], transaction_id)
  assertEq(t['recipient_id'], transaction['recipient_id'])

# Check if download_link is sent.
with Meta(metrics = Metrics()) as meta:
  assertEq(len(meta.meta.metrics.got), 0)
  bob = User(meta, "bob@infinit.io")
  bob.login()
  transaction, res = bob.sendfile(recipient = "alice@infinit.io", initialize = True)
  tid = res['created_transaction_id']
  res = bob.transaction_update(tid, transaction_status.GHOST_UPLOADED)
  assertIn('download_link', res)
  assertIn('transaction_hash', res)
  res = bob.get('transaction/%s' % tid)
  assertIn('download_link', res)
  assertIn('transaction_hash', res)
  res = bob.get('transaction/by_hash/%s' % res['transaction_hash'])
  assertIn('download_link', res)

  transaction, res = bob.sendfile(recipient = "+336000000", initialize = True)
  tid = res['created_transaction_id']
  res = bob.transaction_update(tid, transaction_status.GHOST_UPLOADED)
  assertIn('download_link', res)
  assertIn('transaction_hash', res)
  res = bob.get('transaction/%s' % tid)
  assertIn('download_link', res)
  assertIn('transaction_hash', res)
  res = bob.get('transaction/by_hash/%s' % res['transaction_hash'])
  assertIn('download_link', res)
  assertEq(len(meta.meta.metrics.got), 1)
  metrics = meta.meta.metrics.got['new_ghost']
  assertEq(len(metrics), 2)
  assertEq(set([metric['is_email'] for metric in metrics]), {True, False})
  assertEq(len([metric['user'] for metric in metrics]), 2)
  assertEq(len([metric['ghost_code'] for metric in metrics]), 2)
  assertEq(set([metric['sender'] for metric in metrics]), {str(bob.id)})

from datetime import datetime, timedelta
height_days_ago = datetime.now() - timedelta(days = 8)
two_days_ago = datetime.now() - timedelta(days = 2)

# Expired transactions.
with Meta(metrics = Metrics()) as meta, Trophonius(meta) as trophonius:
  bob = User(meta, "bob@infinit.io")
  bob.login(trophonius = trophonius)
  # Create a transaction (date_string means that the date is represented as a
  # string in the database.
  def populate():
    # Add finished and expired transactions.
    for _ in range(0, 5):
      transaction, res = bob.sendfile(recipient = "alice@infinit.io", initialize = True)
      tid = res['created_transaction_id']
      res = bob.transaction_update(tid, transaction_status.FINISHED)
      meta.database.transactions.update(
        {'_id': bson.ObjectId(tid)},
        {
          '$set': {
            'creation_time': height_days_ago,
          }
        })
    # Add finished ghost uploaded transactions.
    for _ in range(0, 5):
      transaction, res = bob.sendfile(recipient = "alice@infinit.io", initialize = True)
      tid = res['created_transaction_id']
      res = bob.transaction_update(tid, transaction_status.FINISHED)
      meta.database.transactions.update(
        {'_id': bson.ObjectId(tid)},
        {
          '$set': {
            'creation_time': height_days_ago,
            'is_ghost': True,
          }
        })
    # Add pending non expired ghost transactions.
    for _ in range(0, 5):
      transaction, res = bob.sendfile(recipient = "alice@infinit.io", initialize = True)
      tid = res['created_transaction_id']
    return (5, 10)

  def create_transaction(expired = True, is_ghost = False):
    transaction, res = bob.sendfile(recipient = "alice@infinit.io", initialize = True)
    tid = res['created_transaction_id']
    res = bob.transaction_update(tid, transaction_status.GHOST_UPLOADED)
    date = height_days_ago if expired else two_days_ago
    meta.database.transactions.update(
      {'_id': bson.ObjectId(tid)},
      {
        '$set': {
          'creation_time': date,
          'is_ghost': is_ghost,
        }
      })
    return bson.ObjectId(tid), expired and is_ghost

  population = populate()
  meta.meta.forward(timedelta(seconds = 1))
  transactions = []
  count = 2
  import itertools
  for _ in range(0, count):
    for combination in itertools.product(*([[True, False]] * 2)):
      transactions.append(create_transaction(*combination))
  expected_expired = set([t[0] for t in transactions if t[1]])
  assertEq(len(expected_expired), count)
  expired = meta.inner._expired_transactions(
    meta.inner.user_by_id(bson.ObjectId(bob.id), fields = []))
  expired_ids = [t['_id'] for t in expired]
  # Assert transactions marked as expired are the only one matched by
  # _expired_transactions.
  assertEq(set(expired_ids), expected_expired)

  # synchronize will cancel expired transactions only.
  meta.metrics.got = {}
  del bob.notifications[:]
  res = bob.synchronize()
  # Check notifications.
  wait(lambda: len(bob.notifications) >= count, 1)
  notifications = bob.notifications
  notifications = list(filter(lambda x: x['notification_type'] == PEER_TRANSACTION,
                              notifications))
  assertEq(len(notifications), count)
  assertEq(set([bson.ObjectId(n['_id']) for n in notifications]),
           expected_expired)
  # Only canceled.
  statuses = set([n['status'] for n in notifications])
  assertEq(statuses.intersection(set([transaction_status.CANCELED])),
           set([transaction_status.CANCELED]))
  # Final transactions.
  print(expected_expired)
  assertEq(len(res['final_transactions']), len(expected_expired) + population[1])
  def canceled_only(trs):
    return list(filter(lambda x: x['status'] == transaction_status.CANCELED,
                       trs))
  assertEq(len(canceled_only(res['final_transactions'])),
           len(expected_expired))
  assertEq(set(bson.ObjectId(t['id']) for t
               in canceled_only(res['final_transactions'])),
           expected_expired)
  # Transactions.
  assertEq(len(bob.get('transactions?negate=0', {
    'filter': "[%s]" % transaction_status.CANCELED,
  })['transactions']), count)
  assertEq(len(bob.get('transactions?negate=0', {
    'filter': "[%s]" % transaction_status.CANCELED,
  })['transactions']), count)
  # Metrics.
  metrics = meta.metrics.got
  assertEq(len(metrics['ended']), count)
  assert all([m['how_ended'] == 'canceled' for m in metrics['ended']])
  assertEq(
    len(list(filter(lambda x: x['onboarding'] == False, metrics['ended']))),
    count)
  res = bob.synchronize(init = True)
  assertEq(len(res['running_transactions']), population[0] + len(transactions) - count)
  assertEq(len(res['final_transactions']), population[1] + count)
