#!/usr/bin/env python3

from utils import Meta, User, HTTPException
from infinit.oracles.meta.server.transaction_status import INITIALIZED, ACCEPTED, FINISHED

with Meta() as meta:
  bob = User(meta, "bob@infinit.io")
  bob.login()
  bob.sendfile("eve@infinit.io")
  transaction, res = bob.sendfile(recipient = "0666000666", initialize = True)
  assert 'ghost_code' in res['recipient']

  eve = User(meta, "eve@infinit.io")
  eve.login()

  eve.post('ghost/%s/merge' % res['recipient']['ghost_code'])
  try:
    eve.post('ghost/%s/merge' % res['recipient']['ghost_code'])
    assert False
  except HTTPException as e:
    assert e.status == 410

with Meta() as meta:
  bob = User(meta, "bob@infinit.io")
  bob.login()
  transaction, res = bob.sendfile(recipient = "0666000666", initialize = True)
  phone_recipient = res['recipient']
  assert 'ghost_code' in phone_recipient

  transaction, res = bob.sendfile(recipient = "dimrok@infini.io", initialize = True)
  email_recipient = res['recipient']
  assert 'ghost_code' not in email_recipient

  ghost = meta.get('users/%s' % phone_recipient['id'])
  assert 'phone_number' in ghost
  assert 'ghost_code' in ghost
  assert 'ghost_profile' in ghost
  ghost = meta.get('users/%s' % email_recipient['id'])
  assert 'phone_number' not in ghost
  assert 'ghost_code' not in ghost
  assert 'ghost_profile' not in ghost
