#!/usr/bin/env python3

import datetime

from utils import *
import infinit.oracles.meta.server.transaction_status as transaction_status

import bson

with Meta(stripe_api_key = 'sk_test_WtXpwiieEsemLlqrQeKK0qfI') as meta:
  alice = User(meta, "alice@infinit.io")
  alice.login()
  # Send to ghost size limit
  #throws(lambda:
  #    alice.sendfile("bob@infinit.io", total_size = 5000000000),
  #    402)
  # Link quotas
  meta.database.users.update({'accounts.id': 'alice@infinit.io'},
    {'$set': { 'quota.total_link_size': 1000}})
  link = alice.getalink()
  alice.link_update(link, transaction_status.FINISHED)
  # server is updating quota by reading cloud storage file size which is
  # not realy uploaded here, so insert the result ourselve in db
  meta.database.users.update({'accounts.id': 'alice@infinit.io'},
    {'$inc': {'total_link_size': 1100,}})
  meta.database.links.update({'hash': link['hash']},
    {'$set': {'file_size': 1100, 'quota_counted': True}})
  throws(
    lambda: alice.getalink(),
    402)
  # user erases one, below quota now
  alice.link_update(link, transaction_status.DELETED)
  link = alice.getalink()
  alice.link_update(link, transaction_status.FINISHED)


  bob = User(meta, 'bob@infinit.io')
  bob.login()
  me = bob.me
  assertEq(me['plan'], 'basic')
  assert me['features']['nag']
  assert me['features'].get('turbo') is None
  assertEq(me['quota']['total_link_size'], 1e9)
  print(me['id'])
  meta.meta.change_plan(bson.ObjectId(me['id']), 'premium')
  me = bob.me
  assertEq(me['plan'], 'premium')
  assert me['features'].get('nag') is None
  assert me['features'].get('turbo')
  assertEq(me['quota']['total_link_size'], 5e10)
  bob.put('users/%s' % bob.id, {'plan': 'basic'})
  me = bob.me
  assertEq(me['plan'], 'basic')
  assert me['features']['nag']
  assert me['features'].get('turbo') is None
  assertEq(me['quota']['total_link_size'], 1e9)

  # Referral program
  transaction, res = bob.send(recipient = "candy@infinit.io")
  transaction, res = bob.send(recipient = "daniel@infinit.io")
  candy = User(meta, 'candy@infinit.io')
  candy.login()
  c = candy.me
  assertEq(c['quota']['total_link_size'], 15e8)
  b = bob.me
  assertEq(b['quota']['total_link_size'], 2e9)
  candy.send(recipient = "daniel@infinit.io")
  daniel = User(meta, 'daniel@infinit.io')
  daniel.login()
  c = candy.me
  assertEq(c['quota']['total_link_size'], 25e8)
  b = bob.me
  assertEq(b['quota']['total_link_size'], 3e9)
  # Referral through ghost
  transaction, res = bob.send(recipient = 'edgar@infinit.io')
  edgar = User(meta, 'edgar2@infinit.io')
  edgar.login()
  assertEq(edgar.me['quota']['total_link_size'], 1e9)
  gc = meta.database.users.find_one({'accounts.id': 'edgar@infinit.io'})['ghost_code']
  edgar.post('ghost/%s/merge' % gc)
  assertEq(edgar.me['quota']['total_link_size'], 15e8)
  assertEq(bob.me['quota']['total_link_size'], 4e9)
