#!/usr/bin/env python3

from utils import HTTPException, Meta, User

with Meta() as meta:
  wrong_number = '0600000000'
  alice = User(meta, "alice@infinit.io")
  alice.login(country_code = None,
              device_push_token = "31")
  try:
    _, res1 = alice.sendfile(recipient = wrong_number, use_identifier = True, initialize = True)
    assert False
  except HTTPException as e:
    assert e.status == 400
    print(e.content)
    assert wrong_number in e.content['reason']
    assert 'None' in e.content['detail']

with Meta() as meta:
  wrong_email = 'fimrok@akzd@ro.io'
  alice = User(meta, "alice@infinit.io")
  alice.login(country_code = None,
              device_push_token = "31")
  try:
    _, res1 = alice.sendfile(recipient = wrong_email, use_identifier = True, initialize = True)
    assert False
  except HTTPException as e:
    assert e.status == 400
    print(e.content)
    assert wrong_email in e.content['reason']
