#!/usr/bin/env python3

from utils import Meta, User, Trophonius
from infinit.oracles.meta.server.mail import Mailer

class MailService(Mailer):

  def __init__(self, expected_template, sender, recipient):
    super().__init__(True)
    self.__expected_template = expected_template
    self.__sender = sender
    self.__recipient = recipient
    self.__sent = False

  # Override Mailer private __send method.
  def _Mailer__send(self, msg):
    assert str(msg).find(self.__recipient.email) > 0
    assert str(msg).find(self.__expected_template) > 0
    self.__sent = True

  @property
  def sent(self):
    return self.__sent

# Peer online.
with Meta(enable_emails = True) as meta, Trophonius(meta) as trophonius:
  bob = User(meta, "bob@infinit.io")
  alice = User(meta, "alice@infinit.io")
  bob.login()
  alice.login()

  trophonius.connect_user(bob)
  trophonius.connect_user(alice)

  meta.mailer = MailService("accept-file-online-offline", bob, alice)

  transaction, res = bob.sendfile(recipient_id = alice.id)
  assert res['success']

  assert meta.mailer.sent

# Peer offline.
with Meta(enable_emails = True) as meta, Trophonius(meta) as trophonius:
  bob = User(meta, "bob@infinit.io")
  alice = User(meta, "alice@infinit.io")
  bob.login()
  alice.login()

  trophonius.connect_user(bob)

  meta.mailer = MailService("accept-file-only-offline", bob, alice)

  transaction, res = bob.sendfile(recipient_id = alice.id)
  assert res['success']

  assert meta.mailer.sent
