#!/usr/bin/env python3

from utils import *

# Check send to self onboarding emails
with Meta() as meta:
  alice = User(meta, 'alice@infinit.io')
  bob = User(meta, 'bob@infinit.io')
  alice.login()
  alice.sendfile(bob.email)
  assert not meta.emailer.emails
  alice.sendfile(alice.email)
  emails = meta.emailer.emails
  assertEq(len(emails), 1)
  assertEq(emails[0].template, 'send-self-first')
  alice.sendfile(alice.email)
  assert not meta.emailer.emails
