#!/usr/bin/env python3

import copy

from utils import Meta, User, NoOpMailer
from uuid import uuid4

from infinit.oracles.meta.server.transaction_status import CREATED
from infinit.oracles.meta.server.transaction_status import INITIALIZED
from infinit.oracles.meta.server.transaction_status import ACCEPTED
from infinit.oracles.meta.server.transaction_status import FINISHED
from infinit.oracles.meta.server.transaction_status import REJECTED
from infinit.oracles.meta.server.transaction_status import CANCELED
from infinit.oracles.meta.server.transaction_status import FAILED

with Meta() as meta:
  alice_one = User(meta, "alice@infinit.io")
  alice_one.login(uuid4())
  alice_two = copy.deepcopy(alice_one)
  alice_two.login(uuid4())
  assert alice_one.id == alice_two.id
  assert alice_one.device_id != alice_two.device_id

  # Equivalent to sendfile to aliceone (id is the same).
  _, res = alice_one.sendfile(alice_two.id, initialize = True)
  transaction_id = res['created_transaction_id']

  # Can't accept on the same device.
  res = alice_one.update_transaction(transaction_id, ACCEPTED)
  assert res['success'] == False

  # Accept.
  res = alice_two.update_transaction(transaction_id, ACCEPTED)
  print(res)
  assert res['success']

  # Only the recipient should be able to finish the transaction.
  res = alice_one.update_transaction(transaction_id, FINISHED)
  assert res['success'] == False

  # Finish.
  res = alice_two.update_transaction(transaction_id, FINISHED)
  assert res['success']
