#!/usr/bin/env python3

from utils import HTTPException, Meta, User
from bson import ObjectId
from functools import reduce
import sys
from infinit.oracles.meta.server import transaction_status

# Send and merge.
with Meta() as meta:
  alice = User(meta, "alice@infinit.io")
  alice.login()

  ti1 = alice.sendfile(recipient = '+33600000000')[1]['created_transaction_id']
  assert meta.database.users.count() == 2
  ti2 = alice.sendfile(recipient = '+33600000000')[1]['created_transaction_id']
  assert meta.database.users.count() == 2
  assert meta.database.users.find_one(
    {'accounts.id': '+33 6 00 00 00 00'})
  recipient = meta.database.users.find_one(
    {'accounts.id': '+33 6 00 00 00 00'})
  assert len(recipient['ghost_code'])
  alice.transaction_update(ti1, transaction_status.INITIALIZED)
  # Only one is visible.
  assert(len(alice.transactions) == 1)
  bob = User(meta, "bob@infinit.io")
  bob.login()
  assert(len(bob.transactions) == 0)
  bob.post('ghost/%s/merge' % recipient['ghost_code'])
  assert(len(bob.transactions) == 1)
  alice.transaction_update(ti2, transaction_status.INITIALIZED)
  assert(len(alice.transactions) == 2)
  assert(len(bob.transactions) == 2)
  ti3 = alice.sendfile(recipient = '+33600000000')[1]['created_transaction_id']
  alice.transaction_update(ti3, transaction_status.INITIALIZED)
  assert meta.database.users.count() == 3
  assert(len(alice.transactions) == 3)

with Meta() as meta:
  alice = User(meta, "alice@infinit.io")
  alice.login(country_code = "FR", device_push_token = "31")
  ti1 = alice.sendfile(recipient = '+33600000000', use_identifier = True)[1]['created_transaction_id']
  assert meta.database.users.count() == 2
  ti2 = alice.sendfile(recipient = '0600000000', use_identifier = True)[1]['created_transaction_id']
  print(list(meta.database.users.find({}, {'accounts': 1})))
  assert meta.database.users.count() == 2
  assert meta.database.users.find_one(
    {'accounts.id': '+33 6 00 00 00 00'})
  assert meta.database.users.find_one(
    {'accounts.id': '+33 6 00 00 00 00'})
  recipientplus = meta.database.users.find_one(
    {'accounts.id': '+33 6 00 00 00 00'})
  recipient = meta.database.users.find_one(
    {'accounts.id': '+33 6 00 00 00 00'})
  assert recipient['_id'] == recipientplus['_id']
  assert recipient['ghost_code'] == recipientplus['ghost_code']
  alice.transaction_update(ti1, transaction_status.INITIALIZED)
  alice.transaction_update(ti2, transaction_status.INITIALIZED)
  bob = User(meta, "bob@infinit.io")
  bob.login()
  assert(len(bob.transactions) == 0)
  bob.post('ghost/%s/merge' % recipient['ghost_code'])
  assert(len(bob.transactions) == 2)

# Ghost code, one with country code, the other with no country code.
with Meta() as meta:
  alice = User(meta, "alice@infinit.io")
  # Device push token is needed because
  alice.login(country_code = "FR",
              device_push_token = "31")
  _, res0 = alice.sendfile(recipient = '+33600000000', use_identifier = True, initialize = True)
  assert meta.database.users.count() == 2
  _, res1 = alice.sendfile(recipient = '0600000000', use_identifier = True, initialize = True)
  assert meta.database.users.count() == 2
  ti0 = res0['created_transaction_id']
  ti1 = res1['created_transaction_id']
  assert meta.database.users.find_one(
    {'accounts.id': '+33 6 00 00 00 00'})
  assert meta.database.users.find_one(
    {'accounts.id': '+33 6 00 00 00 00'})
  recipientplus = meta.database.users.find_one(
    {'accounts.id': '+33 6 00 00 00 00'})
  recipient = meta.database.users.find_one(
    {'accounts.id': '+33 6 00 00 00 00'})
  extra_transactions = 2
  for _ in range(extra_transactions):
    alice.sendfile(recipient = '0600000000', use_identifier = True, initialize = True)
  assert recipient['_id'] == recipientplus['_id']
  assert recipient['ghost_code'] == recipientplus['ghost_code']
  alice.transaction_update(ti0, transaction_status.INITIALIZED)
  alice.transaction_update(ti1, transaction_status.INITIALIZED)
  alice.transaction_update(ti0, transaction_status.GHOST_UPLOADED)
  alice.transaction_update(ti1, transaction_status.GHOST_UPLOADED)

  ghost_code = res0['recipient']['ghost_code']
  eve = User(meta, "eve@infinit.io")
  eve.login()
  eve.post('ghost/%s/merge' % ghost_code)

  assert len(eve.transactions) == 2 + extra_transactions
  eve.transaction_update(ti0, transaction_status.ACCEPTED)
  eve.transaction_update(ti0, transaction_status.FINISHED)

  eve.transaction_update(ti1, transaction_status.ACCEPTED)
  eve.transaction_update(ti1, transaction_status.FINISHED)
