#!/usr/bin/env python3

from utils import *

with Meta() as meta:
  alice = User(meta, "alice@infinit.io")
  bob = User(meta, "bob@infinit.io")

  bob.login()

  transaction, res = bob.sendfile(recipient = alice.id,
                                  use_identifier = False)
  transaction_id = res['created_transaction_id']

  alice.login()

  res = alice.get('transaction/%s' % transaction_id)

  for key in transaction.keys():
    if key in ['id_or_email', 'device_id']: # Special cases.
      continue
    assertEq(res[key], transaction[key])
  assertEq(res['recipient_id'], transaction['recipient_id'])
