#!/usr/bin/env python3

from utils import Meta, User
from bson import ObjectId
from functools import reduce

from infinit.oracles.meta.transaction_status import CREATED as C
from infinit.oracles.meta.transaction_status import INITIALIZED as I
from infinit.oracles.meta.transaction_status import ACCEPTED as A
from infinit.oracles.meta.transaction_status import FINISHED as F
from infinit.oracles.meta.transaction_status import REJECTED as R
from infinit.oracles.meta.transaction_status import CANCELED as CA
from infinit.oracles.meta.transaction_status import FAILED as FA

def S():
  print("was the same")

def E():
  raise Exception("unreachable")

def O():
  print("ok")

sender_transitions = list()
recipient_transitions = list()

#                          C  I  A  F  R  CA FA
sender_transitions.append([E, O, E, E, E, O, O]) # C
sender_transitions.append([E, S, E, E, E, O, O]) # I
sender_transitions.append([E, E, E, E, E, O, O]) # A
sender_transitions.append([E, O, E, E, E, S, S]) # F
sender_transitions.append([E, E, E, E, E, S, S]) # R
sender_transitions.append([E, E, E, E, E, S, S]) # CA
sender_transitions.append([E, E, E, E, E, S, S]) # FA

#                             C  I  A  F  R  CA FA
recipient_transitions.append([E, E, E, E, E, O, O]) # C
recipient_transitions.append([E, E, O, E, O, O, O]) # I
recipient_transitions.append([E, E, S, O, E, O, O]) # A
recipient_transitions.append([E, E, E, S, E, S, S]) # F
recipient_transitions.append([E, E, E, E, S, S, S]) # R
recipient_transitions.append([E, E, E, S, S, S, S]) # CA
recipient_transitions.append([E, E, E, S, S, S, S]) # FA

def fake_transaction(database, **kwargs):
  database.insert(kwargs)

with Meta() as meta:
  alice = User(meta, "alice@infinit.io")
  bob = User(meta, "bob@infinit.io")

  bob.login()
