#!/usr/bin/env python3

from utils import Meta, User, NoOpMailer

from infinit.oracles.meta.server.transaction_status import FINISHED

class MailService(NoOpMailer):

  def __init__(self, expected_template, recipient_email):
    super().__init__(True)
    self.__expected_template = expected_template
    self.__recipient_email = recipient_email

  def template_message(self, template_name, message):
    merges = {}
    print(template_name, message)
    for entry in message['merge_vars'][0]['vars']:
      merges[entry['name']] = entry['content']
    assert 'note' in merges.keys()
    assert 'file_url' in merges.keys()
    assert 'file_url_urlencoded' in merges.keys()
    assert message['to'][0]['email'] == self.__recipient_email

with Meta() as meta:
  bob = User(meta, "bob@infinit.io")
  bob.login()

  alice_email = 'alice@infinit.io'
  transaction, res = bob.sendfile(recipient_id = alice_email,
                                  initialize = True)
  assert res['success']
  transaction_id = res['created_transaction_id']

  meta.mailer = MailService("send-file-url",
                            recipient_email = alice_email)
  assert meta.mailer.sent == 0

  res = bob.post('transaction/update', {"transaction_id": transaction_id,
                                        "status": FINISHED,
                                        "device_id": str(bob.device_id),
                                        "device_name": bob.device_name})
  assert res['success']
  assert meta.mailer.sent > 0
