#!/usr/bin/env python3.2
from __future__ import print_function

import json
import pythia
import sys
import time
import walrus

import trophonius
import plasma

try:
    meta = trophonius.FakeMeta()
    with meta:
        tropho = trophonius.Trophonius(meta_port = meta.port)
        with tropho:
            print(tropho.port, tropho.host)
            with walrus.Walrus(trophonius_host="127.0.0.1", \
                    trophonius_port=tropho.port) as w:
                meta_client = pythia.Client(server = meta.url)
                res = meta_client.post('/user/login', {
                    'email': 'pif@infinit.io',
                    'password': 'paf'
                    })
                client = plasma.Trophonius("127.0.0.1", int(w.port),
                                           lambda: print('connected'))
                client.connect(res['_id'], res['token'], 'device')
                for i in range(30):
                    notif = client.poll()
                    if i == 15:
                        w.pause()
                    if notif is not None:
                        print(notif)
                    time.sleep(2)
                assert client.retries == 0
                print("quiting")
except:
    print('Trophonius stdout:\n' + tropho.stdout, file = sys.stderr)
    print('Trophonius stderr:\n' + tropho.stderr, file = sys.stderr)
    print('Meta stdout:\n' + meta.stdout, file = sys.stderr)
    print('Meta stderr:\n' + meta.stderr, file = sys.stderr)
    raise
