#!/usr/bin/env python3.2

import json
import pythia
import sys
import time

import trophonius
import plasma

try:
    meta = trophonius.FakeMeta()
    with meta:
        tropho = trophonius.Trophonius(meta_port = meta.port)
        with tropho:
            meta_client = pythia.Client(server = meta.url)
            res = meta_client.post('/user/login', {
                'email': 'pif@infinit.io',
                'password': 'paf'
                })
            client = plasma.Client(tropho.host, tropho.port,
                                   lambda: print('connected'))
            client.connect(res['_id'], res['token'], 'device')
            for i in range(40):
                print(client.poll())
                time.sleep(1)
except:
    print('Trophonius stdout:\n' + tropho.stdout, file = sys.stderr)
    print('Trophonius stderr:\n' + tropho.stderr, file = sys.stderr)
    print('Meta stdout:\n' + meta.stdout, file = sys.stderr)
    print('Meta stderr:\n' + meta.stderr, file = sys.stderr)
    raise
