#!/usr/bin/env python3

# utils first, beware of system OpenSSL.
import utils
from utils import *

import elle.log

from infinit.oracles.transaction import statuses
from infinit.oracles.utils import key

import sisyphus
import sisyphus.boulders.drip

ELLE_LOG_COMPONENT = 'infinit.oracles.sisyphus.boulders.drip'

class ConfirmSignup(sisyphus.boulders.drip.ConfirmSignup):

  def __init__(self, sisyphus):
    super().__init__(sisyphus)
    self.__now = datetime.datetime.utcnow()

  @property
  def now(self):
    return self.__now

  @now.setter
  def now(self, value):
    self.__now = value

  def _pick_template(self, template, users):
    return sisyphus.boulders.drip.Drip._pick_template(
      self, template, users)


def check_mail(mails, recipient, template):
  utils.check_mail(mails, recipient, template)
  assertEq(mails[0][1]['confirm_key'],
           key('/users/%s/confirm-email' % mails[0][1]['user']['id']))

with mongobox.MongoBox() as mongo:
  with Meta(mongo_port = mongo.port, enable_emails = False) as meta:
    emailer = DummyEmailer()
    sisy = sisyphus.Sisyphus(mongo_port = mongo.port,
                                 emailer = emailer)
    gestapo(sisy._Sisyphus__mongo)
    confirm = ConfirmSignup(sisy)

    def forward(duration):
      confirm.now += duration
      meta.now = confirm.now

    # Check nothing is sent with no users
    sisy.boulders_run()
    check_no_mail(emailer.emails)
    # Create user
    sender = user_register(meta, 'sender@infinit.io')
    # Check nothing is sent to a fresh user
    forward(confirm.delay_first_reminder / 2)
    sisy.boulders_run()
    check_no_mail(emailer.emails)
    # Check first mail is sent
    forward(confirm.delay_first_reminder)
    sisy.boulders_run()
    check_mail(emailer.emails,
               'sender@infinit.io', 'drip_confirm-signup_1')
    sisy.boulders_run()
    check_no_mail(emailer.emails)
    # Check no mail is sent to ghosts
    transaction_create(meta, sender, recipient_identifier = 'ghost@infinit.io')
    forward(confirm.delay_first_reminder * 2)
    sisy.boulders_run()
    check_no_mail(emailer.emails)
    # Check leeway starts on ghost registration
    meta.user_register('ghost@infinit.io', '*' * 64, 'Foo Bar')
    sisy.boulders_run()
    check_no_mail(emailer.emails)
    forward(confirm.delay_first_reminder * 1.5)
    sisy.boulders_run()
    check_mail(emailer.emails,
               'ghost@infinit.io', 'drip_confirm-signup_1')
