#!/usr/bin/env python3

# utils first, beware of system OpenSSL.
from utils import *

import elle.log

from infinit.oracles.transaction import statuses

import sisyphus
import sisyphus.boulders.drip

ELLE_LOG_COMPONENT = 'infinit.oracles.sisyphus.boulders.drip'

class DelightSender(sisyphus.boulders.drip.DelightSender):

  def _pick_template(self, template, users):
    return sisyphus.boulders.drip.Drip._pick_template(
      self, template, users)

def check_mail(mails, recipient):
  assert len(mails) == 1
  mail = mails[0]
  assert mail[0] == recipient
  content = mail[1]
  assert content['USER_EMAIL'] == recipient

def send(sender, recipient, files = ['foobar']):
  tid = transaction_create(meta, sender, recipient)
  meta._transaction_update(tid, statuses['ghost_uploaded'],
                           'device', None, sender)
  meta.transaction_download(tid)
  return tid

with mongobox.MongoBox() as mongo:
  with Meta(mongo_port = mongo.port, enable_emails = False) as meta:
    mandrill = Mandrill()
    sisy = sisyphus.Sisyphus(mongo_port = mongo.port,
                             mandrill = mandrill)
    gestapo(sisy._Sisyphus__mongo)
    reminder = DelightSender(sisy)

    # Check nothing is sent with no users
    sisy.boulders_run()
    assert not mandrill.emails

    # Create senders
    ghost_email = 'ghost@infinit.io'
    device = 'device'
    sender1 = meta.user_register('sender1@infinit.io',
                                 '*' * 64, 'Foo Bar')
    sender2 = meta.user_register('sender2@infinit.io',
                                 '*' * 64, 'Foo Bar')
    sender3 = meta.user_register('sender3@infinit.io',
                                 '*' * 64, 'Foo Bar')

    for i in range(reminder.threshold_first):
      sisy.boulders_run()
      assert not mandrill.emails
      send(sender1, ghost_email)
    sisy.boulders_run()
    check_mail(mandrill.emails, 'sender1@infinit.io')

    for i in range(reminder.threshold_first,
                   reminder.threshold_second):
      sisy.boulders_run()
      assert not mandrill.emails
      send(sender1, ghost_email)
    sisy.boulders_run()
    check_mail(mandrill.emails, 'sender1@infinit.io')

    for i in range(reminder.threshold_second,
                   reminder.threshold_third):
      sisy.boulders_run()
      assert not mandrill.emails
      send(sender1, ghost_email)
    sisy.boulders_run()
    check_mail(mandrill.emails, 'sender1@infinit.io')

    send(sender1, ghost_email)
    sisy.boulders_run()
    assert not mandrill.emails
