#!/usr/bin/env python3

import os
import sys
from itertools import chain

SELF = os.path.realpath(__file__)
sys.path.insert(
  0,
  '%s/../lib/python%s.%s' % tuple([os.path.dirname(SELF),
                                   sys.version_info[0],
                                   sys.version_info[1]]))
sys.path.insert(0, '%s/../lib/python' % os.path.dirname(SELF))

# Do not reorder those lines, or a python native module component will
# load the system libcrypto.so, which will prevent loading our
# libcrypto.so through a RPATH on our native module.
import infinit.oracles.sisyphus
import infinit.oracles.sisyphus.boulders
import infinit.oracles.sisyphus.boulders.drip
import infinit.oracles.sisyphus.emailer
import bottle
import elle.log

import optparse
usage = "usage: %prog [options]"
parser = optparse.OptionParser(usage = usage)
parser.add_option('--port',
                  action = 'store',
                  help = 'Port to listen on',
                  default = '8080')
parser.add_option('--mongo-port',
                  action = 'store',
                  help = 'Mongodb port',
                  type = int,
                  default = None)
parser.add_option('--mongo-host',
                  action = 'append',
                  help = 'Mongodb host',
                  type = str,
                  default = None)
parser.add_option('--mongo-replica-set',
                  action = 'store_true',
                  help = 'Use mongo replica set',
                  default = False)

options, _ = parser.parse_args()

args = {}
if options.mongo_host:
  args['mongo_host'] = options.mongo_host

# import mandrill
# mandrill = mandrill.Mandrill(
#   apikey = 'ca159fe5-a0f7-47eb-b9e1-2a8f03b9da86')
# args['emailer'] = infinit.oracles.sisyphus.emailer.MandrillEmailer(
#   mandrill)

import sendwithus
swu = sendwithus.api(
  api_key = 'test_4ab93862c9fa3ced9dc5331d5e70220cbb2ff43d')
args['emailer'] = \
  infinit.oracles.sisyphus.emailer.SendWithUsEmailer(swu)

app = infinit.oracles.sisyphus.Sisyphus(**args)
# infinit.oracles.sisyphus.boulders.drip.AcceptReminder(app)
# infinit.oracles.sisyphus.boulders.drip.ConfirmSignup(app)
# infinit.oracles.sisyphus.boulders.drip.DelightGhost(app)
# infinit.oracles.sisyphus.boulders.drip.DelightRecipient(app)
# infinit.oracles.sisyphus.boulders.drip.DelightSender(app)
# infinit.oracles.sisyphus.boulders.drip.GhostReminder(app)
# infinit.oracles.sisyphus.boulders.drip.Onboarding(app)
infinit.oracles.sisyphus.boulders.drip.WeeklyReport(app)

bottle.run(app = app,
           host = '127.0.0.1',
           port = int(options.port))
