#!/usr/bin/env python3

from utils import Meta, User

class MailService():

  def __init__(self, recipient):
    self.recipient = recipient

  def send_via_mailchimp(self,
                         mail,
                         template_id,
                         subject,
                         from_="Infinit <no-reply@infinit.io>",
                         reply_to=None,
                         encoding='utf8',
                         **kw):
    self.recipient.reset_password_hash = kw['reset_password_hash']

  def send(self,
           email,
           subject,
           content,
           from_="Infinit <no-reply@infinit.io>",
           reply_to=None,
           encoding='utf8',
           attached=None):
    pass

with Meta() as meta:
  email = 'bob@infinit.io'
  fullname = 'bob'

  bob = User(meta, email = email, fullname = fullname)

  meta.mailer = MailService(bob)

  bob.login()
  old_identity = bob.identity
  bob.logout()

  meta.post('lost-password', {"email": email})

  meta.get('reset-accounts/%s' % bob.reset_password_hash)['success']

  assert hasattr(bob, 'reset_password_hash')
  meta.post('reset-accounts/%s' % bob.reset_password_hash, {"password": "new_password"})

  bob.password = "new_password"
  bob.login()

  new_identity = bob.identity

  assert new_identity != old_identity

  bob.logout()

  assert hasattr(bob, 'reset_password_hash')
  meta.post('reset-accounts/%s' % bob.reset_password_hash, {"password": "new_password"})
