#!/usr/bin/env python3

from utils import Meta, User

from infinit.oracles.meta.server import transaction_status
from infinit.oracles.meta import error

class MailService():

  def __init__(self, recipient):
    self.recipient = recipient

  def templated_send(self,
                     **kw):
    self.recipient.reset_password_hash = kw['reset_password_hash']

  def send(self, **kw):
    pass

class Ghost:

  def __init__(self, email):
    self.email = email

with Meta() as meta:
  bob = Ghost(email = 'bob@infinit.io')

  alice = User(meta, email = 'alice@infinit.io', fullname = 'alice')

  # Create a ghost by sending him a file.
  alice.login()
  id = alice.sendfile(bob.email)[1]['created_transaction_id']
  alice.post("transaction/update", {"transaction_id": str(id), "status": transaction_status.INITIALIZED})
  alice.logout()

  meta.mailer = MailService(bob)

  res = meta.post('lost-password', {"email": bob.email})
  assert not res['success']
  assert res['error_code'] == error.UNKNOWN_USER[0]
