#!/usr/bin/env python3

from utils import Meta, User

from infinit.oracles.meta import error

with Meta() as meta:
  res = meta.post('lost-password', {"email": "thisemaildoesntexist@email.com"})
  assert not res['success']
  assert res['error_code'] == error.UNKNOWN_USER[0]

  res = meta.post('lost-password', {"email": "notanemail"})
  assert not res['success']
  assert res['error_code'] == error.UNKNOWN_USER[0]
