#!/usr/bin/env python3

from utils import *

from infinit.oracles.meta import error

with Meta() as meta:
  throws(
    lambda: meta.post(
      'user/%s/lost-password' % 'thisemaildoesntexist@email.com'),
    404)
  throws(lambda: meta.post('/user/%s/lost-password', 'notanemail'),
         400)
