#!/usr/bin/env python3

from utils import *

count = 1

with Meta() as meta:
  res = meta.post(
    'debug/report/user',
    {
      'send': False,
    })
  assertEq(len(meta.emailer.emails), 0)

  res = meta.post(
    'debug/report/user',
    {
      'send': True,
    })
  emails = meta.emailer.emails
  assertEq(len(emails), 1)
  assertEq(emails[0].recipient.email, 'crash@infinit.io')
  assertEq(emails[0].files, None)

  res = meta.post(
    'debug/report/user',
    {
      'send': True,
      'client_os': 'Kanard',
    })
  emails = meta.emailer.emails
  assertEq(len(emails), 1)
  assertEq(emails[0].variables['os'], 'Kanard')
  assertEq(emails[0].files, None)

  res = meta.post(
    'debug/report/user',
    {
      'send': True,
      'client_os': 'Kanard',
      'message': 'Duck are rapists',
    })
  emails = meta.emailer.emails
  assertEq(len(emails), 1)
  assertEq(emails[0].variables['os'], 'Kanard')
  assertEq(emails[0].variables['message'], 'Duck are rapists')
  assertEq(emails[0].files, None)

  res = meta.post(
    'debug/report/user',
    {
      'send': True,
      'client_os': 'Kanard',
      'file': 'Y29udGVudA=='
    })
  emails = meta.emailer.emails
  assertEq(len(emails), 1)
  assertEq(len(emails[0].files), 1)
